"""Every number, table and figure in the rewritten manuscript, generated from archived evidence only.

    python scripts/paper/make_final_tables.py          # writes paper/latex/generated/{numbers.tex, tab_*.tex, fig_*.pdf}

Inputs (all under results/):
  release_pipeline/gate.json                       equivalence to the authors' runners
  release_pipeline/<model>/sweep.jsonl             R1 (shipped seed) and R2 (seeds 0-49)
  release_pipeline/mechanism/<model>.json          R3 interleaving
  release_pipeline/markup/<model>.jsonl            R3 causal test
  release_pipeline/sentinel/<model>.jsonl          R3 deliberate anchors
  matched_detectors/table.json, gradsafe/*         R4
Nothing here reads a model or a GPU. A missing input renders as a visible \\missing{} marker, never a
silent default; `--strict` turns any marker into an error.
"""
from __future__ import annotations

import argparse
import json
import random

import numpy as np
from scipy.stats import spearmanr

from mtkaudit.paths import ROOT
from mtkaudit.results import (RES, RP, GEN, MODELS, MNAME, MMAC, SHIPPED, FAM, FAM_ORDER, f3, f2,
                              load_sweep, by_seed, shipped_metrics, DETECTORS, DCODE, INTERNAL, matched_scores,
                              matched_scores_one, BUDGETS, budget_metrics)
from mtkaudit.texts import is_formatting_row

MISSING = []


def missing(what):
    MISSING.append(what)
    return r"\missing{}"


class Numbers:
    def __init__(self):
        self.items = {}

    def __setitem__(self, name, value):
        assert name.isalpha(), name
        self.items[name] = value

    def tex(self):
        lines = ["% generated by make_final_tables.py -- do not edit",
                 r"\providecommand{\missing}{\textbf{??}}"]
        for k, v in sorted(self.items.items()):
            lines.append(rf"\newcommand{{\n{k}}}{{{v}}}")
        return "\n".join(lines) + "\n"


def r1(N, sweeps):
    rows = {f: {} for f in FAM_ORDER}
    extra = {}
    for m in MODELS:
        met = shipped_metrics(sweeps[m], m)
        if met is None:
            continue
        for f, v in met["families"].items():
            rows[FAM[f]][m] = v
        extra[m] = met
        M = MMAC[m]
        fams = met["families"]
        N[f"{M}MeanAUROC"] = f3(met["mean_auroc"])
        N[f"{M}MeanTPR"] = f3(met["mean_tpr_0.05"])
        N[f"{M}FPR"] = f3(met["realised_fpr"]["0.05"])
        N[f"{M}SAAAUROC"] = f3(fams["saa"]["auroc"])
        N[f"{M}SAATPR"] = f3(fams["saa"]["tpr"]["0.05"])
        N[f"{M}SAATPRten"] = f3(fams["saa"]["tpr"]["0.1"])
        N[f"{M}SAATPRsevenfive"] = f3(fams["saa"]["tpr"]["0.075"])
        N[f"{M}FPRsevenfive"] = f3(met["realised_fpr"]["0.075"])
        au = [v["auroc"] for v in fams.values()]
        tp = [v["tpr"]["0.05"] for v in fams.values()]
        N[f"{M}AUROCmin"], N[f"{M}AUROCmax"] = f3(min(au)), f3(max(au))
        N[f"{M}TPRmin"], N[f"{M}TPRmax"] = f3(min(tp)), f3(max(tp))
        N[f"{M}Spearman"] = f2(spearmanr(au, tp).correlation)
        worst = min(fams, key=lambda f: fams[f]["tpr"]["0.05"])
        N[f"{M}WorstFam"] = FAM[worst]
        N[f"{M}WorstTPR"] = f3(fams[worst]["tpr"]["0.05"])
        N[f"{M}WorstAUROC"] = f3(fams[worst]["auroc"])
        low = [f for f in fams if fams[f]["tpr"]["0.05"] < 0.2 and fams[f]["auroc"] > 0.85]
        N[f"{M}NLowTPRHighAUROC"] = str(len(low))
        s = met["saa850_repaired"]
        N[f"{M}SAAeightAUROC"] = f3(s["auroc"])
        N[f"{M}SAAeightTPR"] = f3(s["tpr"]["0.05"])
        N[f"{M}SAAeightASRhb"] = f3(s["asr_harmbench"])
        N[f"{M}SAAeightASRsr"] = f3(s["asr_strongreject"])
        N[f"{M}SAAeightEASRhb"] = f3(s["easr_harmbench_0.05"])
        N[f"{M}SAAeightEASRsr"] = f3(s["easr_strongreject_0.05"])
        N[f"{M}SAAnosufTPR"] = f3(met["saa850_nosuffix"]["tpr"]["0.05"])
        N[f"{M}PMPFPR"] = f3(met["pmp"]["fpr"]["0.05"])
        N[f"{M}PMPn"] = f"{met['pmp']['n_evaluated']:,}".replace(",", "{,}")
    # GCG at the real-traffic threshold, all models (MTK's Table 9 names no model)
    gcg = {}
    for m in extra:
        f = extra[m]["families"]
        g = f["nanogcg"] if "nanogcg" in f else f["nonagcg"]
        gcg[m] = (g["tpr"]["0.01"], g["tpr"]["0.05"], g["n"])
        N[f"{MMAC[m]}GCGTPRone"], N[f"{MMAC[m]}GCGTPRfive"] = f3(g["tpr"]["0.01"]), f3(g["tpr"]["0.05"])
    oth = [v for m, v in gcg.items() if m != "llama2"]
    if oth:
        N["GCGOtherOneMin"], N["GCGOtherOneMax"] = f3(min(v[0] for v in oth)), f3(max(v[0] for v in oth))
        N["GCGOtherFiveMin"], N["GCGOtherFiveMax"] = f3(min(v[1] for v in oth)), f3(max(v[1] for v in oth))
    pmp = [extra[m]["pmp"]["fpr"]["0.05"] for m in extra]
    if pmp:
        N["PMPFPRMin"], N["PMPFPRMax"] = f3(min(pmp)), f3(max(pmp))
    sp = [spearmanr([v["auroc"] for v in extra[m]["families"].values()],
                    [v["tpr"]["0.05"] for v in extra[m]["families"].values()]).correlation for m in extra]
    if sp:
        N["SpearmanMin"], N["SpearmanMax"] = f2(min(sp)), f2(max(sp))
    # families of similar AUROC, very different detection
    band = [(v["auroc"], v["tpr"]["0.05"], m, f) for m in extra for f, v in extra[m]["families"].items()
            if 0.91 <= v["auroc"] <= 0.93 and v["n"] >= 50]
    if band:
        lo, hi = min(band, key=lambda b: b[1]), max(band, key=lambda b: b[1])
        N["BandN"], N["BandTPRmin"], N["BandTPRmax"] = str(len(band)), f3(lo[1]), f3(hi[1])
        N["BandLoFam"], N["BandLoModel"], N["BandLoAUROC"] = FAM[lo[3]], MNAME[lo[2]], f3(lo[0])
        N["BandHiFam"], N["BandHiModel"], N["BandHiAUROC"] = FAM[hi[3]], MNAME[hi[2]], f3(hi[0])
    for r in sweeps.get("vicuna", []):   # the configured seed, all prompts extracted in one bulk pass
        if r["seed"] == SHIPPED["vicuna"] and r["variant"] == "as_shipped" and r["test_features"] == "allrecords":
            N["VicSAATPRbulk"] = f3(r["metrics"]["families"]["saa"]["tpr"]["0.05"])
            N["VicMeanAUROCbulk"] = f3(r["metrics"]["mean_auroc"])
    # Vicuna: runner batching (exact_shipped) vs one bulk pass (allrecords), same prompts, configured seed
    vl = RP / "vicuna" / "rows.json"
    ex_f, al_f = RP / "vicuna/scores/as_shipped_exact_shipped_seed56.npy", RP / "vicuna/scores/as_shipped_allrecords_seed56.npy"
    if vl.exists() and ex_f.exists() and al_f.exists():
        L_ = json.loads(vl.read_text())
        ex_, al_ = np.load(ex_f).astype(float), np.load(al_f).astype(float)
        d_ = [abs(ex_[r] - al_[L_["allrecords"]["datasets"][nm]["feature_row"][p]])
              for nm, info in L_["exact_shipped"]["datasets"].items() for p, r in enumerate(info["feature_row"]) if r >= 0]
        N["VicBatchMaxDiff"], N["VicBatchMedDiff"] = f"{max(d_):.3f}", f"{np.median(d_):.4f}"
    sizes = [r["metrics"]["n_calibration"] for m in MODELS for r in sweeps[m]]
    if sizes:
        N["CalSizeMin"], N["CalSizeMax"] = str(min(sizes)), str(max(sizes))
    ship_sizes = [extra[m]["n_calibration"] for m in extra]
    if ship_sizes:
        N["CalShipMin"], N["CalShipMax"] = str(min(ship_sizes)), str(max(ship_sizes))
    allau = [v["auroc"] for m in extra for v in extra[m]["families"].values()]
    if allau:
        N["AllMeanAUROCmin"] = f3(min(extra[m]["mean_auroc"] for m in extra))
        N["AllMeanAUROCmax"] = f3(max(extra[m]["mean_auroc"] for m in extra))
    # table
    L = [r"\begin{table*}[t]", r"\centering",
         r"\caption{The authors' release as shipped (commit \texttt{c5e2f18}, each model at its configured seed). "
         r"AUROC is the release's own metric; TPR is the detection rate at the threshold calibrated to a 5\% "
         r"benign false-positive budget on held-out ToxicChat prompts sharing no text with the evaluated ones "
         r"(\nCalShipMin--\nCalShipMax\ distinct prompts), and the realised FPR on the "
         r"release's 500 evaluated benign prompts is given at the foot. $n$: prompts per family (per model where they "
         r"differ: Llama-2/Llama-3/Mistral/Vicuna). Bold: TPR below 0.2 at AUROC of at least 0.85.}",
         r"\label{tab:r1}", r"\footnotesize", r"\setlength{\tabcolsep}{5pt}",
         r"\begin{tabular}{lr" + "rr" * len(MODELS) + "}", r"\toprule",
         " & & " + " & ".join(rf"\multicolumn{{2}}{{c}}{{{MNAME[m]}}}" for m in MODELS) + r" \\",
         " ".join(rf"\cmidrule(lr){{{3 + 2 * i}-{4 + 2 * i}}}" for i in range(len(MODELS))),
         "Family & $n$ & " + " & ".join(["AUROC & TPR"] * len(MODELS)) + r" \\", r"\midrule"]
    for f in FAM_ORDER:
        cells = []
        for m in MODELS:
            v = rows[f].get(m)
            if v is None:
                cells += [missing(f"R1 {m} {f}")] * 2
                continue
            t = f3(v["tpr"]["0.05"])
            if v["tpr"]["0.05"] < 0.2 and v["auroc"] >= 0.85:
                t = rf"\textbf{{{t}}}"
            cells += [f3(v["auroc"]), t]
        ns = [rows[f][m]["n"] for m in MODELS if m in rows[f]]
        n = str(ns[0]) if len(set(ns)) == 1 else "/".join(str(x) for x in ns)
        L.append(f"{f} & {n} & " + " & ".join(cells) + r" \\")
    L.append(r"\midrule")
    for label, key in (("SAA-850 transfer set", "saa850_repaired"), ("\\quad same goals, no suffix", "saa850_nosuffix")):
        cells = []
        for m in MODELS:
            if m not in extra:
                cells += [missing("R1 saa850")] * 2
                continue
            v = extra[m][key]
            t = f3(v["tpr"]["0.05"])
            if v["tpr"]["0.05"] < 0.2 and v["auroc"] >= 0.85:
                t = rf"\textbf{{{t}}}"
            cells += [f3(v["auroc"]), t]
        L.append(f"{label} & 850 & " + " & ".join(cells) + r" \\")
    L.append(r"\midrule")
    L.append("Mean (12 families) & & " + " & ".join(
        f"{f3(extra[m]['mean_auroc'])} & {f3(extra[m]['mean_tpr_0.05'])}" if m in extra else "\\missing{} & \\missing{}"
        for m in MODELS) + r" \\")
    L.append("Realised FPR & 500 & " + " & ".join(
        rf"\multicolumn{{2}}{{c}}{{{f3(extra[m]['realised_fpr']['0.05'])}}}" if m in extra else r"\multicolumn{2}{c}{\missing{}}"
        for m in MODELS) + r" \\")
    L.append("SAA-850 eASR (HB / SR) & 850 & " + " & ".join(
        rf"\multicolumn{{2}}{{c}}{{{f3(extra[m]['saa850_repaired']['easr_harmbench_0.05'])} / "
        rf"{f3(extra[m]['saa850_repaired']['easr_strongreject_0.05'])}}}" if m in extra else r"\multicolumn{2}{c}{\missing{}}"
        for m in MODELS) + r" \\")
    L.append("SAA-850 ASR, no defence (HB / SR) & 850 & " + " & ".join(
        rf"\multicolumn{{2}}{{c}}{{{f3(extra[m]['saa850_repaired']['asr_harmbench'])} / "
        rf"{f3(extra[m]['saa850_repaired']['asr_strongreject'])}}}" if m in extra else r"\multicolumn{2}{c}{\missing{}}"
        for m in MODELS) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    (GEN / "tab_r1.tex").write_text("\n".join(L) + "\n")
    return extra


def rule_x(N):
    """The AUROC > 1 - alpha rule across detectors (rule_crossdetector.py)."""
    p = RES / "rule_test" / "cross_detector.json"
    if not p.exists():
        missing("rule test")
        return
    r = json.loads(p.read_text())
    N["RuleXN"] = f"{r['n_cells']:,}".replace(",", "{,}")
    N["RuleXAll"] = f"{100 * r['overall']['agreement']:.1f}"
    N["RuleXConc"] = f"{100 * r['by_concentration']['lt_0.5']['agreement']:.1f}"
    N["RuleXSpread"] = f"{100 * r['by_concentration']['ge_1']['agreement']:.1f}"
    N["RuleXMTK"] = f"{100 * r['by_detector']['MTK']['agreement']:.1f}"
    pos = float(np.mean([c["tpr"] > 0.5 for c in r["cells"]]))
    N["RuleXBaseline"] = f"{100 * max(pos, 1 - pos):.1f}"      # always predicting the more common outcome


def draw_baseline(N):
    """Runs missing some family, against a binormal detector with the same per-family AUROCs (draw_miss_baseline.py)."""
    p = RES / "rule_test" / "draw_miss_baseline_v2.json"      # shared threshold per run
    if not p.exists():
        missing("draw baseline")
        return
    r = json.loads(p.read_text())
    for v, tag in (("as_shipped", ""), ("bank_only", "BankOnly")):
        x = r["variants"][v]
        N[f"DrawBase{tag}Exp"] = f"{x['expected_runs_with_miss_binormal']:.0f}"
        N[f"DrawBase{tag}HiddenRuns"] = str(x["runs_with_miss_at_auroc_ge_0.85"])
        N[f"DrawBase{tag}N"] = str(x["n_runs"])
    from scipy.stats import norm
    N["DrawBaseTPRatEightyFive"] = f"{100 * norm.cdf(np.sqrt(2) * norm.ppf(0.85) - norm.ppf(0.95)):.0f}"   # binormal, 5%


def anchor_length(N):
    """Is the formatting rows' pull a general short-anchor effect? (anchor_length_check.py)"""
    p = RES / "rule_test" / "anchor_length_v2.json"      # v1 stored shares scaled by 1/1600 (same orderings)
    if not p.exists():
        missing("anchor length")
        return
    r = json.loads(p.read_text())
    s2 = r["llama2"]["saa"]
    N["AnchorLtwoTopMedLen"] = f"{s2['median_len_top20']:.0f}"
    N["AnchorLtwoTopPct"] = f"{s2['percentile_of_median_top20']:.0f}"
    rho = [r[m]["saa"]["spearman_length_vs_share"] for m in MODELS]
    N["AnchorRhoMin"], N["AnchorRhoMax"] = f"{min(rho):+.2f}", f"{max(rho):+.2f}"


def mtk_bank_noise(N):
    """The GradSafe noise test applied to MTK's bank-only draws (mtk_bank_noise.py; fixed before computing)."""
    p = RES / "uncertainty" / "mtk_bank_noise.json"
    if not p.exists():
        missing("mtk bank noise")
        return
    r = json.loads(p.read_text())["models"]
    for m in MODELS:
        M = MMAC[m]
        N[f"MTKNoise{M}Ratio"] = f"{r[m]['ratio']:.2f}" if r[m]["testable"] else "--"
    N["MTKNoiseUntestable"] = str(sum(not r[m]["testable"] for m in MODELS))
    N["MTKNoisePass"] = str(sum(r[m]["exceeds_sampling_noise"] for m in MODELS))


def tc_labels(N):
    """ToxicChat's own labels for the evaluated benign prompts, and the Dolly thresholds' FPR on the human-labelled
    non-toxic ones (toxicchat_label_check.py)."""
    p = RES / "uncertainty" / "toxicchat_labels.json"
    if not p.exists():
        missing("toxicchat labels")
        return
    r = json.loads(p.read_text())["models"]
    cnt = lambda lab: [r[m]["counts"]["benign_eval"].get(lab, 0) for m in MODELS]
    N["TCLabHumanMin"], N["TCLabHumanMax"] = str(min(cnt("human"))), str(max(cnt("human")))
    N["TCLabToxicMin"], N["TCLabToxicMax"] = str(min(cnt("toxic"))), str(max(cnt("toxic")))
    for sub, w in (("human", "Human"), ("clean", "Clean")):
        v = [r[m]["dolly_threshold_fpr"]["MTK"][sub] for m in MODELS]
        N[f"TCLabMTK{w}Min"], N[f"TCLabMTK{w}Max"] = f3(min(v)), f3(max(v))
        dets = r[MODELS[0]]["dolly_threshold_fpr"]
        N[f"TCLabDetsEveryModel{w}"] = str(sum(all(r[m]["dolly_threshold_fpr"][d][sub] > 0.05 for m in MODELS)
                                               for d in dets))


def review3(N):
    """Numbers added for the third outside review (2026-09-29): exact exceedance test for the Dolly thresholds,
    goal overlap with MTK's anchors, an equal-variance Gaussian reading of one AUROC, bank-only family spans, and the
    targeted interventions against their control arm."""
    from scipy.stats import betabinom, norm
    # (1) exact exceedance test, one-sided at 5% (a 95% predictive bound under exchangeability). np.quantile's
    # interpolated 95% threshold lies between the (k+1)-th and k-th highest of the n calibration scores,
    # k = floor(0.05 (n-1)) + 1. The count of m evaluation prompts above the j-th highest calibration score is
    # Beta-Binomial(m, j, n-j+1), and the count above the threshold is at most the count above the (k+1)-th highest,
    # so the conservative exact test uses j = k+1. Holm's step-down procedure is applied across the 40
    # detector x model x dataset tests.
    sm = json.loads((RES / "dolly_calibration" / "summary_v2.json").read_text())
    wc = json.loads((RES / "wildchat" / "summary.json").read_text())
    dets = ("MTK", "Probe", "GradSafe", "HiddenDetect", "Windowed PPL")

    def order_stat(n):
        j = int(np.floor(0.05 * (n - 1))) + 2
        return j, n - j + 1

    def holm(pv, a=0.05):
        keys = sorted(pv, key=pv.get)
        rej = {q: False for q in pv}
        for r, q in enumerate(keys):
            if pv[q] > a / (len(keys) - r):
                break
            rej[q] = True
        return rej

    pv = {}
    for m in MODELS:
        a, b = order_stat(sm[m]["_split"]["n_calibration"])
        for d in dets:
            for ds, fpr in (("TC", sm[m][d]["dolly"]["fpr_toxicchat_eval"]), ("WC", wc[m][d]["dolly"]["fpr_wildchat_eval"])):
                x = int(round(fpr * 500))
                assert abs(x / 500 - fpr) < 1e-9
                pv[(m, d, ds)] = float(betabinom.sf(x - 1, 500, a, b))
    sig, sig_h = {q: v < 0.05 for q, v in pv.items()}, holm(pv)
    for suf, sg in (("", sig), ("Holm", sig_h)):
        N[f"ExcEveryBoth{suf}"] = str(sum(all(sg[(m, d, ds)] for m in MODELS for ds in ("TC", "WC")) for d in dets))
        N[f"ExcGSPairs{suf}"] = str(sum(sg[(m, "GradSafe", ds)] for m in MODELS for ds in ("TC", "WC")))
        N[f"ExcHDPairs{suf}"] = str(sum(sg[(m, "HiddenDetect", ds)] for m in MODELS for ds in ("TC", "WC")))
        N[f"ExcTCPairs{suf}"] = str(sum(sg[(m, d, "TC")] for m in MODELS for d in dets))
        N[f"ExcWCPairs{suf}"] = str(sum(sg[(m, d, "WC")] for m in MODELS for d in dets))
    ns = sorted({sm[m]["_split"]["n_calibration"] for m in MODELS})
    js = {order_stat(n)[0] for n in ns}
    assert len(js) == 1
    j0 = js.pop()
    N["ExcOrderStat"], N["ExcOrderStatUpper"] = str(j0), str(j0 - 1)   # the threshold lies between the two
    # expected null exceedance j / (n + 1) and the one-sided 95% bound for 500 evaluation prompts (199-200 calibration)
    nul = [100 * order_stat(n)[0] / (n + 1) for n in ns]
    N["ExcNullPctMin"], N["ExcNullPctMax"] = f"{min(nul):.2f}", f"{max(nul):.2f}"
    his = [float(betabinom.ppf(0.95, 500, *order_stat(n))) / 500 for n in ns]
    N["ExcChanceHiMin"], N["ExcChanceHiMax"] = f3(min(his)), f3(max(his))
    N["ExcCalMin"], N["ExcCalMax"] = str(min(ns)), str(max(ns))
    # the same conservative test on ToxicChat's human-labeled non-toxic prompts (m = 217-241 per model)
    tl = json.loads((RES / "uncertainty" / "toxicchat_labels.json").read_text())["models"]
    pvh = {}
    for m in MODELS:
        h = tl[m]["counts"]["benign_eval"]["human"]
        a, b = order_stat(sm[m]["_split"]["n_calibration"])
        for d in dets:
            f = tl[m]["dolly_threshold_fpr"][d]["human"]
            x = int(round(f * h))
            assert abs(x / h - f) < 1e-9
            pvh[(m, d)] = float(betabinom.sf(x - 1, h, a, b))
    for suf, sg in (("", {q: v < 0.05 for q, v in pvh.items()}), ("Holm", holm(pvh))):
        N[f"TCLabSigEveryModel{suf}"] = str(sum(all(sg[(m, d)] for m in MODELS) for d in dets))
        N[f"TCLabHDSig{suf}"] = str(sum(sg[(m, "HiddenDetect")] for m in MODELS))
    # WildChat jailbreak-marker control, pair by pair: change in FPR, and pairs still beyond the bound (m = 490)
    ch, kept = [], 0
    for m in MODELS:
        a, b = order_stat(sm[m]["_split"]["n_calibration"])
        for d in dets:
            v = wc[m][d]["dolly"]
            mk = 500 - wc["wildchat_eval_marker_excluded"]
            x = int(round(v["fpr_wildchat_no_markers_eval"] * mk))
            assert abs(x / mk - v["fpr_wildchat_no_markers_eval"]) < 1e-9
            ch.append(abs(v["fpr_wildchat_no_markers_eval"] - v["fpr_wildchat_eval"]))
            kept += sig[(m, d, "WC")] and float(betabinom.sf(x - 1, mk, a, b)) < 0.05
    N["WCMarkerMaxChange"] = f3(max(ch))
    N["WCMarkerSigKept"] = str(kept)
    # (2) goal overlap (goal_overlap.py)
    go = json.loads((RES / "uncertainty" / "goal_overlap.json").read_text())["models"]
    with_goal = {f for m in MODELS for f, v in go[m].items() if v.get("goal_field") and f != "SAA-850"}
    N["GOFamsGoal"] = str(len({f.replace("nonagcg", "nanogcg") for f in with_goal}))
    N["GOFamsOverlap"] = str(len({f.replace("nonagcg", "nanogcg") for m in MODELS for f, v in go[m].items()
                                  if v.get("goal_field") and f != "SAA-850" and v["n_overlap"] > 0}))
    big = [(m, f, v) for m in MODELS for f, v in go[m].items() if v.get("goal_field") and v["n"] - v["n_overlap"] >= 50]
    for d in ("MTK", "Probe"):
        N[f"GO{d}MaxDiff"] = f3(max(abs(v[d]["tpr_non_overlap"] - v[d]["tpr_all"]) for _, _, v in big))
    missed = [(m, f, v) for m, f, v in big if v["MTK"]["tpr_all"] < 0.2]
    N["GOMissedN"] = str(len(missed))
    N["GOMissedKept"] = str(sum(v["MTK"]["tpr_non_overlap"] < 0.2 for _, _, v in missed))
    N["GOMissedNonMin"] = str(min(v["n"] - v["n_overlap"] for _, _, v in missed))
    N["GOMissedNonMax"] = str(max(v["n"] - v["n_overlap"] for _, _, v in missed))
    N["GOMissedNonTPRMax"] = f3(max(v["MTK"]["tpr_non_overlap"] for _, _, v in missed))
    small = [(m, f, v) for m in MODELS for f, v in go[m].items() if v.get("goal_field") and v["n_overlap"] > 0
             and v["n"] - v["n_overlap"] < 50]
    assert {f for _, f, _ in small} == {"tap", "pap_gpt3.5", "pap_gpt4", "pap_llama2", "nanogcg"}, small
    assert all(f == "nanogcg" and m == "llama2" for m, f, v in small if f == "nanogcg")
    N["GOSmallNonMax"] = str(max(v["n"] - v["n_overlap"] for m, f, v in small if f != "nanogcg"))
    N["GOLtwoNanoNon"] = str(go["llama2"]["nanogcg"]["n"] - go["llama2"]["nanogcg"]["n_overlap"])
    N["GOLthreeSAAeightNon"] = f3(go["llama3"]["SAA-850"]["MTK"]["tpr_non_overlap"])
    N["GOLthreeSAAeightOverlapN"] = str(go["llama3"]["SAA-850"]["n_overlap"])
    # (3) equal-variance Gaussian with MTK's Llama-3 SAA AUROC: TPR at 5% FPR
    a = shipped_metrics(load_sweep("llama3"), "llama3")["families"]["saa"]["auroc"]
    N["GaussLthreeSAATPR"] = f3(float(norm.cdf(np.sqrt(2) * norm.ppf(a) - norm.ppf(0.95))))
    # (4) bank-only redraws: families of 50+ prompts whose 5% TPR spans at least 0.3 across draws
    for m in MODELS:
        dr = by_seed(load_sweep(m), m, "bank_only")
        fams = next(iter(dr.values()))["families"]
        span = {f: [x["families"][f]["tpr"]["0.05"] for x in dr.values()] for f, v in fams.items() if v["n"] >= 50}
        N[f"BankSpan{MMAC[m]}N"] = str(sum(max(v) - min(v) >= 0.3 for v in span.values()))
        if m == "llama3":
            N["BankSpanLthreeZuluMin"], N["BankSpanLthreeZuluMax"] = f3(min(span["zulu"])), f3(max(span["zulu"]))
    # (5) targeted interventions against the ordinary-PKU control, bank by bank (3 banks x 3 SAA-shaped variants)
    for m in MODELS:
        rs = [json.loads(l) for l in (RP / "sentinel_v2" / f"{m}.jsonl").read_text().splitlines()]
        ctrl = {r["bank_seed"]: r for r in rs if r["arm"] == "ordinary" and r["dose"] == 200}
        do, dsa = [], []
        for r in rs:
            if r["arm"] in ("nosuffix", "shufsuffix", "randsuffix") and r["dose"] == 200:
                c = ctrl[r["bank_seed"]]
                do.append(r["mean_tpr_non_saa_0.05"] - c["mean_tpr_non_saa_0.05"])
                dsa.append(r["saa850_eval_half"]["tpr_0.05"] - c["saa850_eval_half"]["tpr_0.05"])
        M = MMAC[m]
        N[f"SentCtrl{M}OtherMin"], N[f"SentCtrl{M}OtherMax"] = f"{min(do):+.3f}", f"{max(do):+.3f}"
        N[f"SentCtrl{M}Drops"] = str(sum(x < 0 for x in do))
        N[f"SentCtrl{M}SAAMin"], N[f"SentCtrl{M}SAAMax"] = f"{min(dsa):+.3f}", f"{max(dsa):+.3f}"



def gradsafe_v4(N):
    """Thirty GradSafe reference sets on Llama-2 (gradsafe_refset_v4.py; pre-registered)."""
    p = RES / "uncertainty" / "gradsafe_refsets_v4.json"
    if not p.exists():
        missing("gradsafe v4")
        return
    r = json.loads(p.read_text())
    N["GSFourN"] = str(r["n_sets"])
    for key, tag in (("mean_auroc", "MeanAUROC"), ("saa_tpr", "SAATPR"), ("saa_auroc", "SAAAUROC"), ("worst_tpr", "Worst")):
        for q in ("min", "median", "max"):
            N[f"GSFour{tag}{q}"] = f3(r[key][q])
    N["GSFourBelow"], N["GSFourAbove"] = str(r["sets_saa_tpr_below_0.2"]), str(r["sets_saa_tpr_above_0.5"])
    N["GSFourRho"] = f"{r['spearman_mean_auroc_vs_saa_tpr']:+.2f}"
    N["GSFourRatio"] = f"{r['ratio']:.1f}"
    N["GSFourB"] = f"{r['B']:,}".replace(",", "{,}")


def wildchat(N):
    """The second real-user distribution (wildchat_select.py, wildchat_summary.py; pre-registered)."""
    p, s = RES / "wildchat" / "summary.json", RES / "wildchat" / "selection.json"
    if not (p.exists() and s.exists()):
        missing("wildchat")
        return
    r, sel = json.loads(p.read_text()), json.loads(s.read_text())
    h = r["headline"]
    N["WCPool"] = f"{sel['counts']['pool_after_dedup']:,}".replace(",", "{,}")
    N["WCConversations"] = f"{sel['counts']['conversations']:,}".replace(",", "{,}")
    N["WCPairs"], N["WCDollyAbove"] = str(h["n_pairs"]), str(h["dolly_on_wildchat_above_budget"])
    N["WCDollyMin"], N["WCDollyMax"] = f3(h["dolly_on_wildchat_min"]), f3(h["dolly_on_wildchat_max"])
    N["WCMTKRatioMin"], N["WCMTKRatioMax"] = f"{min(h['mtk_dolly_on_wildchat_ratio']):.1f}", f"{max(h['mtk_dolly_on_wildchat_ratio']):.1f}"
    N["WCTCtoWCMin"], N["WCTCtoWCMax"] = f3(h["toxicchat_on_wildchat"][0]), f3(h["toxicchat_on_wildchat"][1])
    N["WCWCtoTCMin"], N["WCWCtoTCMax"] = f3(h["wildchat_on_toxicchat"][0]), f3(h["wildchat_on_toxicchat"][1])
    N["WCCrossMin"] = f3(min(h["toxicchat_on_wildchat"][0], h["wildchat_on_toxicchat"][0]))
    N["WCCrossMax"] = f3(max(h["toxicchat_on_wildchat"][1], h["wildchat_on_toxicchat"][1]))
    N["WCInDistMin"], N["WCInDistMax"] = f3(h["wildchat_on_wildchat"][0]), f3(h["wildchat_on_wildchat"][1])
    N["WCNoMarkersMin"], N["WCNoMarkersMax"] = f3(h["dolly_on_wildchat_no_markers"][0]), f3(h["dolly_on_wildchat_no_markers"][1])
    N["WCMarkerExcluded"] = str(r["wildchat_eval_marker_excluded"])
    every = [d for d in ("MTK", "GradSafe", "HiddenDetect", "Windowed PPL", "Probe")
             if all(r[m][d]["dolly"]["fpr_wildchat_eval"] > 0.05 for m in MODELS)]
    N["WCDetsEveryModel"] = str(len(every))
    N["HDAboveWC"] = str(sum(r[m]["HiddenDetect"]["dolly"]["fpr_wildchat_eval"] > 0.05 for m in MODELS))
    N["HDAboveTC"] = str(sum(r[m]["HiddenDetect"]["dolly"]["fpr_toxicchat_eval"] > 0.05 for m in MODELS))
    tc_every = [d for d in ("MTK", "GradSafe", "HiddenDetect", "Windowed PPL", "Probe")
                if all(r[m][d]["dolly"]["fpr_toxicchat_eval"] > 0.05 for m in MODELS)]
    N["TCDetsEveryModel"] = str(len(tc_every))


def pauc_vs_tpr(N):
    """AUROC and partial AUROC against detection at the operating point (pauc_vs_tpr.py; pre-registered)."""
    p = RES / "rule_test" / "pauc_vs_tpr.json"
    if not p.exists():
        missing("pauc vs tpr")
        return
    r = json.loads(p.read_text())
    N["PAUCN"] = str(r["n_points"])
    N["PAUCRhoAUROC"], N["PAUCRhoPAUC"] = f"{r['spearman_auroc_vs_tpr']:.2f}", f"{r['spearman_pauroc_vs_tpr']:.2f}"
    N["PAUCHidden"] = str(r["high_auroc_low_tpr"])
    N["PAUCHiddenAbove"] = str(r["high_auroc_low_tpr_with_pauroc_above_0.75"])
    N["PAUCLthreeSAA"] = f"{r['llama3_mtk_saa']['pauroc_0.05']:.2f}"


def mistral_offset(N):
    """The release's one-block layer offset on Mistral, re-extracted aligned (mistral_offset.py)."""
    p = RP / "mistral_offset" / "metrics.json"
    if not p.exists():
        missing("mistral offset")
        return
    r = json.loads(p.read_text())
    for tag, k in (("Ship", "as_shipped"), ("Aligned", "aligned")):
        f = r[k]["families"]
        N[f"MisOff{tag}MeanAUROC"], N[f"MisOff{tag}MeanTPR"] = f3(r[k]["mean_auroc"]), f3(r[k]["mean_tpr_0.05"])
        N[f"MisOff{tag}AutoDAN"], N[f"MisOff{tag}DrAttack"] = f3(f["autodan"]["tpr"]["0.05"]), f3(f["drattack"]["tpr"]["0.05"])
        N[f"MisOff{tag}SAA"] = f3(f["saa"]["tpr"]["0.05"])
        w = min((v["tpr"]["0.05"], n) for n, v in f.items() if v["n"] >= 50)
        N[f"MisOff{tag}Worst"], N[f"MisOff{tag}WorstTPR"] = FAM[w[1]], f3(w[0])
    N["MisOffN"] = f"{r['n_prompts']:,}".replace(",", "{,}")


def fig_calibration(N):
    """Fig. 1 candidate: MTK's scores on Llama-3 for curated and real benign prompts and SAA, with the 5% thresholds
    set on each benign set. Gaussian KDE with Scott's bandwidth per row, each row scaled to its own peak."""
    import matplotlib
    matplotlib.use("Agg")
    matplotlib.rcParams["pdf.fonttype"] = 42
    import matplotlib.pyplot as plt
    from scipy.stats import gaussian_kde
    from mtkaudit.matched import calibration_rows_v2
    m = "llama3"
    items, dets = matched_scores(m)
    s = np.asarray(dets["MTK"], float)
    rows = lambda pop, fam=None: [i["row"] for i in items if i["population"] == pop and (fam is None or i["family"] == fam)]
    dol = np.load(RES / "dolly_calibration" / f"{m}_dolly_scores.npy").astype(float)
    sp = json.loads((RES / "dolly_calibration" / "split_v2" / f"{m}.json").read_text())
    t_dolly = float(np.quantile(dol[sp["calibration_idx"]], 0.95))
    t_real = float(np.quantile(s[calibration_rows_v2(items)], 0.95))
    series = [("Dolly", "curated instructions", dol[sp["evaluation_idx"]], "#2a78d6", "Dolly"),
              ("ToxicChat", "real-user prompts", s[rows("benign_eval")], "#2a78d6", "Real"),
              ("SAA", "released file, one request", s[rows("release_attack", "saa")], "#eb6834", "SAA"),
              ("SAA-850", "850 distinct requests", s[rows("saa850_repaired")], "#eb6834", "SAAeight")]
    allv = np.concatenate([x for _, _, x, _, _ in series])
    lo, hi = float(allv.min()), float(np.percentile(allv, 99.7))
    pad = 0.04 * (hi - lo)
    grid = np.linspace(lo - pad, hi + pad, 600)
    pct = lambda v: f"{100 * v:.1f}\\%" if 0 < v < 0.01 else f"{100 * v:.0f}\\%"
    with matplotlib.rc_context({"font.family": "STIXGeneral", "mathtext.fontset": "stix", "font.size": 8}):
        fig, ax = plt.subplots(figsize=(3.45, 2.25))
        step = 1.15
        for k, (name, sub, x, col, tag) in enumerate(series):
            base = (len(series) - 1 - k) * step
            dens = gaussian_kde(x)(grid)
            dens = dens / dens.max()
            ax.fill_between(grid, base, base + dens, color=col, alpha=0.22, lw=0)
            ax.plot(grid, base + dens, color=col, lw=1.0)
            ax.plot([grid[0], grid[-1]], [base, base], color="#b8b7b3", lw=0.5)
            ax.text(grid[0] - 0.01 * (hi - lo), base + 0.32, f"{name}\n", ha="right", va="center", fontsize=8,
                    color="#0b0b0b")
            ax.text(grid[0] - 0.01 * (hi - lo), base + 0.22, sub, ha="right", va="center", fontsize=6.8,
                    color="#52514e")
            for t, key in ((t_dolly, "Dolly"), (t_real, "Real")):
                v = float((x > t).mean())
                N[f"FigCal{tag}Above{key}"] = f3(v)
                ax.text(t + 0.012 * (hi - lo), base + 0.62, pct(v).replace("\\", ""), fontsize=7.5, color="#0b0b0b",
                        ha="left", va="center",
                        bbox=dict(boxstyle="round,pad=0.12", fc="white", ec="none", alpha=0.85))
        top = (len(series) - 1) * step + 1.12
        ax.axvline(t_dolly, color="#0b0b0b", lw=0.9, ls=(0, (3, 2)), ymax=0.93)
        ax.axvline(t_real, color="#0b0b0b", lw=0.9, ymax=0.93)
        ax.text(t_dolly - 0.012 * (hi - lo), top + 0.05, "5% threshold\nset on Dolly", ha="right", va="bottom",
                fontsize=7.2)
        ax.text(t_real + 0.012 * (hi - lo), top + 0.05, "5% threshold set\non real-user prompts", ha="left", va="bottom",
                fontsize=7.2)
        ax.set_ylim(-0.08, top + 0.55)
        ax.set_xlim(grid[0], grid[-1])
        ax.set_yticks([])
        for sp_ in ("left", "right", "top"):
            ax.spines[sp_].set_visible(False)
        ax.spines["bottom"].set_color("#8a8984")
        ax.tick_params(axis="x", colors="#52514e", labelsize=7.2, length=2)
        ax.set_xlabel("MTK anomaly score (Llama-3, release as shipped)", fontsize=7.6, color="#0b0b0b")
        fig.savefig(GEN / "fig_calibration.pdf", bbox_inches="tight", pad_inches=0.02)
        plt.close(fig)
    N["FigCalThrDolly"], N["FigCalThrReal"] = f"{t_dolly:.3f}", f"{t_real:.3f}"


def fig_overview():
    """Schematic: where reference data and calibration data enter a model-internal detector."""
    import matplotlib
    matplotlib.use("Agg")
    matplotlib.rcParams["pdf.fonttype"] = 42
    import matplotlib.pyplot as plt
    from matplotlib.patches import FancyBboxPatch
    with matplotlib.rc_context({"font.family": "STIXGeneral", "mathtext.fontset": "stix"}):
        fig, ax = plt.subplots(figsize=(3.45, 2.05))
        ax.set_xlim(0, 100), ax.set_ylim(0, 64), ax.axis("off")
        ref, cal, box = "#1f77b4", "#d62728", "#444444"

        def node(x, y, w, h, text, color=box, fill="white", size=7):
            ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.3,rounding_size=1.5", lw=0.8,
                                        ec=color, fc=fill))
            ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=size, linespacing=1.05)

        def arrow(x0, y0, x1, y1, color=box):
            ax.annotate("", xy=(x1, y1), xytext=(x0, y0),
                        arrowprops=dict(arrowstyle="-|>", lw=0.8, color=color, shrinkA=0, shrinkB=0, mutation_scale=6))
        y, h = 24, 11
        boxes = [(0.5, 10, "prompt"), (14.5, 18, "hidden states\nor gradients"), (36.5, 18, "score against\nreferences"),
                 (58.5, 23, "threshold at the\n$(1-\\alpha)$ quantile"), (85.5, 14, "flag\nor pass")]
        for x, w, t in boxes:
            node(x, y, w, h, t, size=6.2)
        for (x0, w0, _), (x1, _, _) in zip(boxes, boxes[1:]):
            arrow(x0 + w0 + 0.4, y + h / 2, x1 - 0.4, y + h / 2)
        node(2, 44, 96, 18, "reference data (R2): MTK's 1,600 anchors $\\to$ rank trajectory\n$\\to$ Isolation Forest; "
             "GradSafe's 2+2 prompts; the probe's\nlabelled anchors; HiddenDetect's refusal tokens",
             color=ref, fill="#eaf2fb", size=7)
        arrow(45.5, 43.4, 45.5, 35.4, ref)
        node(11, 1, 67, 15, "calibration data (R1): benign prompts, curated\n(Dolly) or real user traffic (ToxicChat)",
             color=cal, fill="#fbeaea", size=7)
        arrow(70, 16.6, 70, 23.6, cal)
        node(81, 1, 18.5, 15, "operating\npoint (R3):\nper-family TPR\nat realised FPR", color=box,
             fill="#f2f2f2", size=5.4)
        arrow(92.5, 23.4, 92.5, 16.6, box)
        fig.savefig(GEN / "fig_overview.pdf", bbox_inches="tight", pad_inches=0.01)
        plt.close(fig)


def fig_budget(extra):
    import matplotlib
    matplotlib.use("Agg")
    matplotlib.rcParams["pdf.fonttype"] = 42     # embed TrueType, not Type 3 (IEEE PDF requirements)
    import matplotlib.pyplot as plt
    fig, axes = plt.subplots(1, 4, figsize=(7.0, 1.9), sharey=True)
    for ax, m in zip(axes, MODELS):
        if m not in extra:
            ax.set_title(MNAME[m] + " (missing)")
            continue
        met = extra[m]
        ts = sorted(met["realised_fpr"], key=float)
        x = [met["realised_fpr"][t] for t in ts]
        for f, v in met["families"].items():
            y = [v["tpr"][t] for t in ts]
            name = FAM[f]
            if name in ("SAA", "Zulu", "AutoDAN"):
                ax.plot(x, y, marker="o", ms=2.5, lw=1.4, label=name,
                        color={"SAA": "C3", "Zulu": "C0", "AutoDAN": "C2"}[name])
            else:
                ax.plot(x, y, lw=0.6, color="0.75", zorder=0)
        ax.axvline(met["realised_fpr"]["0.05"], color="k", lw=0.6, ls="--")
        ax.set_title(f"{MNAME[m]} (AUROC {met['mean_auroc']:.3f})", fontsize=8)
        ax.set_xlabel("realised benign FPR", fontsize=7)
        ax.tick_params(labelsize=7)
        ax.set_xlim(0, 0.21)
    axes[0].set_ylabel("detection rate (TPR)", fontsize=7)
    axes[0].legend(fontsize=7, loc="lower right", frameon=False)
    fig.tight_layout(pad=0.3)
    fig.savefig(GEN / "fig_budget.pdf")
    plt.close(fig)


# ------------------------------------------------------------------------------------------------ #
def markup_counts(model, recs):
    """Number of PKU formatting rows ('[\\list]', '[list]') in each seed's malicious bank."""
    import sys
    sys.path.insert(0, str(ROOT))
    from mtkaudit import release as rd
    pku = rd.COPY / "datasets/train_data/PKU-SafeRLHF-prompts_3-6k.txt"
    with pku.open("r", encoding="utf-8", errors="ignore", newline="") as fh:
        rows = [l for l in fh.readlines() if l.strip()]
    markup = {i for i, r in enumerate(rows) if r.strip() in ("[\\list]", "[list]")}
    out = {}
    for r in recs:
        if r["seed"] in out:
            continue
        if r.get("bank_sources"):
            src = next(s for s in r["bank_sources"] if s["path"].endswith("PKU-SafeRLHF-prompts_3-6k.txt"))
            used = src["source_indices"]
        else:
            fp = rd.import_release()
            used = random.Random(fp.stable_seed(r["seed"], "train:malicious:PKU-SafeRLHF-prompts_3-6k.txt")) \
                .sample(range(len(rows)), 600)
        out[r["seed"]] = len(markup & set(used))
    return out


def r2(N, sweeps):
    L = [r"\begin{table*}[!t]", r"\centering",
         r"\caption{Reference-bank sensitivity of MTK, as the release's own seed exposes it. Upper block: "
         r"\texttt{--seed} $s\in\{0,\dots,49\}$ plus the configured seed, which redraws the bank, the "
         r"evaluation sample and the forest together, as shipped. Lower block: only the bank is redrawn; the "
         r"evaluation sample and the forest stay at the configured seed. Median [min, max] over draws; TPR at the "
         r"5\% budget; worst family: the lowest TPR among families of at least 50 prompts. Rank: the "
         r"configured seed's position by mean AUROC. Llama-2's and Mistral's configured seeds (27, 47) lie inside "
         r"0--49, so those models have 50 draws; the others have 51.}",
         r"\label{tab:r2}", r"\footnotesize", r"\setlength{\tabcolsep}{3.5pt}",
         r"\begin{tabular}{lrllllrrr}", r"\toprule",
         r"Model & Draws & Mean AUROC & SAA TPR & Worst-family TPR & Realised FPR & "
         r"\multicolumn{2}{c}{SAA TPR} & Rank \\",
         r"\cmidrule(lr){7-8}",
         r" & & & & & & $>0.5$ & $<0.05$ & \\"]
    stats = {}
    worst = lambda x: min(v["tpr"]["0.05"] for v in x["families"].values() if v["n"] >= 50)
    for variant, title in (("as_shipped", "Bank, evaluation sample and forest redrawn (as shipped)"),
                           ("bank_only", "Bank redrawn; evaluation sample and forest fixed")):
        L += [r"\midrule", rf"\multicolumn{{9}}{{l}}{{\emph{{{title}}}}} \\"]
        for m in MODELS:
            d = by_seed(sweeps[m], m, variant)
            if variant == "as_shipped":
                stats[m] = d
            ship = SHIPPED[m]
            M = MMAC[m] + ("BankOnly" if variant == "bank_only" else "")
            if ship not in d or len(d) < 2:
                L.append(f"{MNAME[m]} & " + " & ".join([missing(f"R2 {m} {variant}")] * 8) + r" \\")
                continue
            def cell(fn):
                v = np.array([fn(x) for x in d.values()])
                return f"{np.median(v):.3f} [{v.min():.3f}, {v.max():.3f}]"
            ma = {s_: x["mean_auroc"] for s_, x in d.items()}
            rank = 1 + sum(v > ma[ship] for v in ma.values())
            saa = [x["families"]["saa"]["tpr"]["0.05"] for x in d.values()]
            w = [worst(x) for x in d.values()]
            gt, lt = sum(t > 0.5 for t in saa), sum(t < 0.05 for t in saa)
            L.append(f"{MNAME[m]} & {len(d)} & {cell(lambda x: x['mean_auroc'])} & "
                     f"{cell(lambda x: x['families']['saa']['tpr']['0.05'])} & {cell(worst)} & "
                     f"{cell(lambda x: x['realised_fpr']['0.05'])} & {gt} & {lt} & {rank} \\\\")
            N[f"{M}Draws"] = str(len(d))
            N[f"{M}ShipRank"] = str(rank)
            N[f"{M}SAATPRgtHalf"] = str(gt)
            N[f"{M}SAATPRltFive"] = str(lt)
            N[f"{M}LotteryMeanAUROCmin"] = f3(min(ma.values()))
            N[f"{M}LotteryMeanAUROCmax"] = f3(max(ma.values()))
            N[f"{M}LotteryMeanAUROCmed"] = f3(float(np.median(list(ma.values()))))
            N[f"{M}LotteryMeanAUROCsd"] = f3(float(np.std(list(ma.values()), ddof=1)))
            if variant == "as_shipped":
                _MED[m] = float(np.median(list(ma.values())))
                _SD[m] = float(np.std(list(ma.values()), ddof=1))
                if len(_SD) == 4:
                    N["LotterySDMin"], N["LotterySDMax"] = f3(min(_SD.values())), f3(max(_SD.values()))
            if variant == "as_shipped" and len(_MED) == 4:
                N["LotteryMedMin"], N["LotteryMedMax"] = f3(min(_MED.values())), f3(max(_MED.values()))
            N[f"{M}LotterySAATPRmin"] = f3(min(saa))
            N[f"{M}LotterySAATPRmax"] = f3(max(saa))
            N[f"{M}LotterySAATPRmed"] = f3(float(np.median(saa)))
            N[f"{M}WorstFamMax"] = f3(max(w))
            N[f"{M}WorstFamBelowTwo"] = str(sum(x < 0.2 for x in w))
            others = sorted(v for s_, v in ma.items() if s_ != ship)
            N[f"{M}ShipMinusMedian"] = f3(ma[ship] - float(np.median(others)))
            sp = spearmanr([x["mean_auroc"] for x in d.values()], saa).correlation
            N[f"{M}LotterySpearman"] = f2(sp) if np.isfinite(sp) else "n/a"
            if variant == "as_shipped":
                fams = next(iter(d.values()))["families"].keys()
                span = {f: max(x["families"][f]["tpr"]["0.05"] for x in d.values()) -
                           min(x["families"][f]["tpr"]["0.05"] for x in d.values()) for f in fams}
                top = max(span, key=span.get)
                N[f"{MMAC[m]}MaxSpanFam"] = FAM[top]
                N[f"{MMAC[m]}MaxSpan"] = f3(span[top])
            else:   # legacy names used in the text
                N[f"{MMAC[m]}BankOnlySAATPRmin"], N[f"{MMAC[m]}BankOnlySAATPRmax"] = f3(min(saa)), f3(max(saa))
                N[f"{MMAC[m]}BankOnlyMeanAUROCmin"] = f3(min(ma.values()))
                N[f"{MMAC[m]}BankOnlyMeanAUROCmax"] = f3(max(ma.values()))
                N[f"{MMAC[m]}BankOnlySAATPRgtHalf"] = str(gt)
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    (GEN / "tab_r2.tex").write_text("\n".join(L) + "\n")
    # in how many draws does some family (at least 50 prompts) fail at the budget? (as shipped; and bank only)
    for variant, tag in (("as_shipped", ""), ("bank_only", "BankOnly")):
        tot = below2 = below1 = 0
        for m in MODELS:
            d = by_seed(sweeps[m], m, variant)
            if len(d) < 2:
                continue
            w = [worst(x) for x in d.values()]
            tot += len(w)
            below2 += sum(t < 0.2 for t in w)
            below1 += sum(t < 0.1 for t in w)
        N[f"Draws{tag}Total"] = str(tot)
        N[f"Draws{tag}WorstBelowTwo"] = str(below2)
        N[f"Draws{tag}WorstBelowOne"] = str(below1)
    cells = [(x["families"]["saa"]["auroc"] > 1 - a, x["families"]["saa"]["tpr"][t] > 0.5)
             for m in MODELS for x in stats[m].values() for t, a in (("0.05", 0.05), ("0.1", 0.10))]
    if cells:
        N["SAARuleN"] = str(len(cells))
        N["SAARuleAgree"] = f"{100 * np.mean([p == q for p, q in cells]):.1f}"
    other = [(v["auroc"] > 1 - a, v["tpr"][t] > 0.5)
             for m in MODELS for x in stats[m].values() for f, v in x["families"].items()
             if f != "saa" and v["n"] >= 50 for t, a in (("0.05", 0.05), ("0.1", 0.10))]
    if other:
        N["OtherRuleAgree"] = f"{100 * np.mean([p == q for p, q in other]):.1f}"
    return stats


def ci_table(N):
    """Headline operating points with 95% bootstrap intervals (results/uncertainty/bootstrap.json)."""
    p = RES / "uncertainty" / "bootstrap.json"
    if not p.exists():
        (GEN / "tab_ci.tex").write_text(r"\missing{}" + "\n")
        missing("bootstrap")
        return
    bs = json.loads(p.read_text())
    rows = [("MTK", "llama2", "saa"), ("MTK", "llama3", "saa"), ("MTK", "vicuna", "saa"), ("MTK", "mistral", "autodan"),
            ("GradSafe", "llama2", "zulu"), ("HiddenDetect", "vicuna", "saa")]
    ci = lambda c: f"{c['point']:.3f} [{c['lo']:.2f}, {c['hi']:.2f}]"
    L = [r"\begin{table}[!t]", r"\centering",
         r"\caption{Selected operating points at the nominal 5\% budget with 95\% bootstrap intervals. Each "
         rf"replicate ($B={bs['B']}$) resamples the calibration prompts and recomputes the threshold, and resamples "
         r"the evaluated benign prompts and the family's prompts. Intervals describe finite-sample uncertainty "
         r"at one reference bank, not variation across banks (Table~\ref{tab:r2}). GS: GradSafe (official "
         r"code); HD: HiddenDetect; FPR: realised benign false-positive rate. Each released family has 500 prompts; "
         r"the released SAA prompts share one request, so SAA-850 (850 distinct behaviours) is added below.}",
         r"\label{tab:ci}", r"\footnotesize", r"\setlength{\tabcolsep}{2pt}",
         r"\begin{tabular}{lrll}", r"\toprule",
         r"Detector, model, family & AUROC & TPR & FPR \\", r"\midrule"]
    for det, m, f in rows:
        c = bs["models"][m]["detectors"][det]
        n = bs["models"][m]["family_n"][f]
        name = {"GradSafe": "GradSafe", "HiddenDetect": "HiddenDetect", "MTK": "MTK"}[det]
        short = {"GradSafe": "GS", "HiddenDetect": "HD", "MTK": "MTK"}[name]
        L.append(f"{short}, {MNAME[m]}, {FAM[f]} & {c['auroc_' + f]['point']:.3f} & "
                 f"{ci(c['tpr_' + f + '_0.05'])} & {ci(c['fpr_0.05'])} \\\\")
        key = f"{MMAC[m]}{ {'MTK': 'MTK', 'GradSafe': 'GS', 'HiddenDetect': 'HD'}[det] }{f.capitalize()}".replace(" ", "")
        for k, lab in ((f"auroc_{f}", "AUROC"), (f"tpr_{f}_0.05", "TPR"), ("fpr_0.05", "FPR")):
            N[f"{key}{lab}"] = f3(c[k]["point"])
            N[f"{key}{lab}lo"] = f3(c[k]["lo"])
            N[f"{key}{lab}hi"] = f3(c[k]["hi"])
    s8p = RES / "uncertainty" / "saa850.json"
    if s8p.exists():
        s8 = json.loads(s8p.read_text())
        L.append(r"\midrule")
        for det, m in (("MTK", "llama2"), ("MTK", "llama3"), ("MTK", "vicuna"), ("HiddenDetect", "vicuna")):
            c, f8 = bs["models"][m]["detectors"][det], s8["models"][m][det]
            short = {"HiddenDetect": "HD", "MTK": "MTK"}[det]
            L.append(f"{short}, {MNAME[m]}, SAA-850 & {f8['auroc']['point']:.3f} & {ci(f8['tpr_0.05'])} & {ci(c['fpr_0.05'])} \\\\")
            key = f"{MMAC[m]}{short}SAAeight"
            N[f"{key}CITPR"], N[f"{key}CITPRlo"], N[f"{key}CITPRhi"] = (f3(f8["tpr_0.05"]["point"]), f3(f8["tpr_0.05"]["lo"]),
                                                                       f3(f8["tpr_0.05"]["hi"]))
            N[f"{key}CIAUROC"] = f3(f8["auroc"]["point"])
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    (GEN / "tab_ci.tex").write_text("\n".join(L) + "\n")
    # text macros: eASR intervals (MTK, both judges), 1% intervals, paired GradSafe-MTK difference
    for m in MODELS:
        c = bs["models"][m]["detectors"]["MTK"]
        M = MMAC[m]
        for k, lab in (("easr_hb_0.05", "EASRhb"), ("easr_sr_0.05", "EASRsr"), ("mean_tpr_0.01", "MeanTPRone"),
                       ("tpr_saa_0.05", "SAATPR"), ("fpr_0.01", "FPRone"), ("fpr_0.05", "FPRfive")):
            N[f"{M}MTK{lab}CIlo"], N[f"{M}MTK{lab}CIhi"] = f3(c[k]["lo"]), f3(c[k]["hi"])
    widths = [c["mean_tpr_0.01"]["hi"] - c["mean_tpr_0.01"]["lo"]
              for m in MODELS for d, c in bs["models"][m]["detectors"].items() if d != "Windowed PPL"]
    N["OneBudgetCIWidthMax"] = f3(max(widths))
    N["OneBudgetCIWidthMin"] = f3(min(widths))
    fw = [c["fpr_0.01"]["hi"] - c["fpr_0.01"]["lo"] for m in MODELS for c in bs["models"][m]["detectors"].values()]
    N["FPROneCIWidthMax"] = f3(max(fw))
    d = bs["models"]["llama2"]["paired_differences"]["GradSafe-MTK:mean_tpr_0.05"]
    N["LtwoGSminusMTKMeanTPRfive"], N["LtwoGSminusMTKMeanTPRfivelo"], N["LtwoGSminusMTKMeanTPRfivehi"] = \
        f"{d['point']:+.3f}", f"{d['lo']:+.3f}", f"{d['hi']:+.3f}"
    mis = bs["models"]["mistral"]["detectors"]["MTK"]["tpr_saa_0.05"]
    N["MisMTKSAATPRCIlo"], N["MisMTKSAATPRCIhi"] = f3(mis["lo"]), f3(mis["hi"])
    rp = RES / "uncertainty" / "gradsafe_refsets_v3.json"   # B = 20,000
    if rp.exists():
        r = json.loads(rp.read_text())
        N["GSRefPairs"], N["GSRefPairsDiffer"] = str(r["n_pairs"]), str(r["n_pairs_differ"])
        N["GSRefB"] = f"{r['B']:,}".replace(",", "{,}")
        N["GSRefPairsDifferHolm"] = str(r["n_pairs_differ_holm"])
        vs = {k.split("-")[1]: v for k, v in r["pairs"].items() if k.startswith("official-")}
        N["GSRefVsOfficialDiffer"] = str(sum(v["excludes_zero"] for v in vs.values()))
        low = sorted((v for v in vs.values() if v["excludes_zero"]), key=lambda v: -v["diff"])
        N["GSRefLowSAA"] = ", ".join(f3(r["sets"][k]["saa_tpr"]) for k, v in sorted(vs.items(), key=lambda kv: r["sets"][kv[0]]["saa_tpr"])
                                     if v["excludes_zero"])
        big = max(vs.values(), key=lambda v: v["diff"])
        N["GSRefBigDiff"], N["GSRefBigDiffLo"], N["GSRefBigDiffHi"] = f"{big['diff']:+.3f}", f"{big['ci'][0]:+.2f}", f"{big['ci'][1]:+.2f}"
    gs = bs["models"]["llama2"]["detectors"]["GradSafe"]["tpr_saa_0.05"]
    N["LtwoGSSAATPRCIlo"], N["LtwoGSSAATPRCIhi"] = f"{gs['lo']:.2f}", f"{gs['hi']:.2f}"


def fig_lottery(stats, markups):
    import matplotlib
    matplotlib.use("Agg")
    matplotlib.rcParams["pdf.fonttype"] = 42     # embed TrueType, not Type 3 (IEEE PDF requirements)
    import matplotlib.pyplot as plt
    fig, axes = plt.subplots(2, 4, figsize=(7.0, 3.1), sharex="col")
    sc = None
    for j, m in enumerate(MODELS):
        d = stats.get(m, {})
        if len(d) < 2:
            axes[0, j].set_title(MNAME[m] + " (missing)", fontsize=8)
            continue
        seeds = sorted(d)
        x = [d[s]["mean_auroc"] for s in seeds]
        c = [markups.get(m, {}).get(s, 0) for s in seeds]
        ship = SHIPPED[m]
        for i, (key, lab) in enumerate(((lambda v: v["families"]["saa"]["tpr"]["0.05"], "SAA TPR at 5% budget"),
                                        (lambda v: v["families"]["saa"]["auroc"], "SAA AUROC"))):
            ax = axes[i, j]
            y = [key(d[s]) for s in seeds]
            sc = ax.scatter(x, y, c=c, cmap="viridis", vmin=0, vmax=3, s=11, lw=0, alpha=0.75)
            ax.scatter([d[ship]["mean_auroc"]], [key(d[ship])], marker="*", s=80, facecolor="none",
                       edgecolor="C3", lw=1.0)
            ax.tick_params(labelsize=7)
            ax.set_ylim(-0.04, 1.04) if i == 0 else ax.set_ylim(0.2, 1.0)
            if j == 0:
                ax.set_ylabel(lab, fontsize=8)
            if i == 0:
                ax.set_title(MNAME[m], fontsize=9)
            else:
                ax.set_xlabel("mean AUROC (12 families)", fontsize=8)
    fig.tight_layout(pad=0.3, rect=(0, 0, 0.915, 1))
    cax = fig.add_axes([0.93, 0.15, 0.012, 0.7])
    cb = fig.colorbar(sc, cax=cax, ticks=[0, 1, 2, 3])
    cb.set_label("formatting rows in bank", fontsize=7.5)
    cb.ax.tick_params(labelsize=7)
    fig.savefig(GEN / "fig_lottery.pdf")
    plt.close(fig)


# ------------------------------------------------------------------------------------------------ #
def r3(N, sweeps, markups):
    # interleaving
    pops = [("benign_eval", "Benign (evaluated)"), ("pmp_non_member", "Pseudo-malicious benign"),
            ("saa", "SAA (released)"), ("saa850_repaired", "SAA-850"), ("saa850_nosuffix", "SAA-850, no suffix"),
            ("zulu", "Zulu"), ("autodan", "AutoDAN"), ("pair", "PAIR")]
    have = {}
    for m in MODELS:
        p = RP / "mechanism_v2" / f"{m}.json"
        if p.exists():
            have[m] = json.loads(p.read_text())
    show = [m for m in MODELS if m in have]
    env = "table*" if len(show) > 2 else "table"
    L = [rf"\begin{{{env}}}[t]", r"\centering",
         r"\caption{What the rank feature sees, at each model's configured seed. $\bar m$: malicious anchors "
         r"ranked ahead of the $k$ nearest benign anchors, averaged over those anchors and all layers "
         r"(Eq.~\ref{eq:identity}); IQR: interquartile range of the anomaly score minus the 5\% threshold; "
         r"Det.: detected at the 5\% budget.}",
         r"\label{tab:r3}", r"\footnotesize", r"\setlength{\tabcolsep}{2.5pt}",
         r"\begin{tabular}{l" + "rrr" * len(show) + "}", r"\toprule"]
    L.append(" & " + " & ".join(rf"\multicolumn{{3}}{{c}}{{{MNAME[m]}}}" for m in show) + r" \\")
    L.append(" ".join(rf"\cmidrule(lr){{{2 + 3 * i}-{4 + 3 * i}}}" for i in range(len(show))))
    L.append("Population & " + " & ".join([r"$\bar m$ & IQR & Det."] * len(show)) + r" \\")
    L.append(r"\midrule")
    for key, label in pops:
        cells = []
        for m in show:
            eps = have[m]["endpoints"]
            ep = (eps["final"] if "final" in eps else eps["colon"])["populations"].get(key)
            if ep is None:
                cells += ["--"] * 3
                continue
            q = ep["margin_iqr"]
            cells += [f"{ep['mean_interleaving']:.1f}", f"{q[1] - q[0]:.3f}", f3(ep["flagged_0.05"])]
        L.append(f"{label} & " + " & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", rf"\end{{{env}}}"]
    (GEN / "tab_r3.tex").write_text("\n".join(L) + "\n")
    if have:
        names = [MNAME[m] for m in MODELS if m in have]
        N["IdentityModels"] = "all four models" if len(names) == 4 else ", ".join(names[:-1]) + " and " + names[-1]
        diffs = [ep["identity"]["max_abs_diff_release_vs_rebuilt"] for rep in have.values() for ep in rep["endpoints"].values()]
        exact = [ep["identity"]["max_abs_diff_ours_vs_release"] for rep in have.values() for ep in rep["endpoints"].values()]
        N["IdentityMaxDiff"] = f"{max(diffs):.1e}".replace("e-05", r"\times10^{-5}").replace("e-06", r"\times10^{-6}")
        N["IdentityLoopDiff"] = "0" if max(exact) == 0 else f"{max(exact):.1e}"
    for m, rep in have.items():
        M = MMAC[m]
        eps = rep["endpoints"]
        ep = eps["final"] if "final" in eps else eps["colon"]
        P = ep["populations"]
        N[f"{M}IdentityDiff"] = f"{ep['identity']['max_abs_diff_release_vs_rebuilt']:.1e}"
        N[f"{M}MbarBenign"] = f"{P['benign_eval']['mean_interleaving']:.2f}"
        N[f"{M}MbarSAA"] = f"{P['saa']['mean_interleaving']:.2f}"
        N[f"{M}MbarSAAnosuf"] = f"{P['saa850_nosuffix']['mean_interleaving']:.1f}"
        q = P["saa"].get("margin_iqr")
        if q:
            N[f"{M}SAAIQRlo"], N[f"{M}SAAIQRhi"] = f"{q[0]:+.3f}", f"{q[1]:+.3f}"
            qb = P["benign_eval"]["margin_iqr"]
            N[f"{M}BenIQRlo"], N[f"{M}BenIQRhi"] = f"{qb[0]:+.3f}", f"{qb[1]:+.3f}"
            N[f"{M}SAAIQRwidth"] = f3(q[1] - q[0])
            N[f"{M}BenIQRwidth"] = f3(qb[1] - qb[0])
        top = P["saa"]["top_interleaving_anchors"]
        N[f"{M}SAATopAnchorShare"] = f"{100 * top[0]['share_of_query_layers']:.0f}"
        N[f"{M}SAATopMarkup"] = str(sum(1 for t in top[:5] if is_formatting_row(t["text80_sha256"])))
        if "autodan" in P:
            qa = P["autodan"]["margin_iqr"]
            N[f"{M}AutoDANIQRlo"], N[f"{M}AutoDANIQRhi"] = f"{qa[0]:+.3f}", f"{qa[1]:+.3f}"
    # markup counts vs SAA AUROC across draws
    for m in MODELS:
        d = by_seed(sweeps[m], m, "as_shipped")
        mk = markups.get(m, {})
        if len(d) > 3 and mk:
            seeds = sorted(set(d) & set(mk))
            sp = spearmanr([mk[s] for s in seeds], [d[s]["families"]["saa"]["auroc"] for s in seeds]).correlation
            N[f"{MMAC[m]}MarkupSpearman"] = f2(sp)
            N[f"{MMAC[m]}ShipMarkup"] = str(mk.get(SHIPPED[m], "?"))
            n3 = [s for s in seeds if mk[s] >= 3]
            N[f"{MMAC[m]}DrawsThreeMarkup"] = str(len(n3))
            for n in range(0, 5):
                sel = [d[s]["families"]["saa"]["auroc"] for s in seeds if mk[s] == n]
                word = ["zero", "one", "two", "three", "four"][n]
                if sel:
                    N[f"{MMAC[m]}MarkupAUROC{word}"] = f"{np.median(sel):.2f}"
                    N[f"{MMAC[m]}MarkupN{word}"] = str(len(sel))
    # causal markup test
    L = [r"\begin{table}[t]", r"\centering",
         r"\caption{Llama-2: changing only the formatting rows in the malicious pool (the Mistral and Llama-3 tests, which "
         r"change nothing, are reported in the text). Evaluation sample and forest at the "
         r"configured seed; threshold recalibrated per arm. \emph{Remove}: each drawn formatting row replaced by an "
         r"unused ordinary PKU prompt. \emph{Insert}: ordinary anchors replaced by formatting rows until the bank "
         r"holds three. \emph{Control}: the same number of ordinary anchors replaced by other ordinary PKU "
         r"prompts. Configured ($n$): the configured bank, holding $n$ formatting rows. Other [$b$]: medians over "
         r"the $b$ banks among seeds 0--9 holding at least one formatting row (for removal) or fewer than three "
         r"(for insertion).}",
         r"\label{tab:markup}", r"\footnotesize", r"\setlength{\tabcolsep}{3pt}",
         r"\begin{tabular}{llrrrr}", r"\toprule",
         r"Bank & Arm & \multicolumn{2}{c}{SAA} & SAA TPR & Mean \\",
         r"\cmidrule(lr){3-4}",
         r" & & AUROC & TPR & at 10\% & AUROC \\", r"\midrule"]
    any_markup = False
    for m in MODELS:
        p = RP / "markup_v2" / f"{m}.jsonl"
        if not p.exists():
            continue
        recs = [json.loads(l) for l in p.read_text().splitlines()]
        any_markup = True
        ship = SHIPPED[m]
        groups = [] if m != "llama2" else [
            ("Configured ({n})", [r for r in recs if r["bank_seed"] == ship],
             ("none", "remove", "remove_control")),
            ("Other, $\\geq1$", [r for r in recs if r["bank_seed"] != ship and r["n_markup_drawn"] > 0],
             ("none", "remove", "remove_control")),
            ("Other, $<3$", [r for r in recs if r["bank_seed"] != ship and r["n_markup_drawn"] < 3],
             ("none", "insert3", "insert3_control"))]
        label = {"none": "as drawn", "remove": "remove", "remove_control": "control",
                 "insert3": "insert", "insert3_control": "control"}
        for title, sel, arms in groups:
            if not sel:
                continue
            n_banks = len({r["bank_seed"] for r in sel})
            first = True
            for arm in arms:
                rows = [r for r in sel if r["arm"] == arm]
                if not rows:
                    continue
                med = lambda k: f"{np.median([r[k] for r in rows]):.3f}"
                head = title.format(n=sel[0]["n_markup_drawn"]) if first else ""
                if first and "Configured" not in title:
                    head += f" [{n_banks}]"
                L.append(f"{head} & {label[arm]} & {med('saa_auroc')} & {med('saa_tpr_0.05')} & "
                         f"{med('saa_tpr_0.1')} & {med('mean_auroc')} \\\\")
                first = False
            L.append(r"\midrule")
        M = MMAC[m]
        for r in recs:
            if r["bank_seed"] != ship:
                continue
            tag = {"none": "Ship", "remove": "ShipRemove", "insert3": "ShipInsert", "insert3_control": "ShipControl",
                   "remove_control": "ShipRemoveControl"}[r["arm"]]
            N[f"{M}Markup{tag}SAATPR"] = f3(r["saa_tpr_0.05"])
            N[f"{M}Markup{tag}SAATPRten"] = f3(r["saa_tpr_0.1"])
            N[f"{M}Markup{tag}SAAAUROC"] = f3(r["saa_auroc"])
            N[f"{M}Markup{tag}SAAeightTPR"] = f3(r["saa850_tpr_0.05"])
            N[f"{M}Markup{tag}MeanAUROC"] = f3(r["mean_auroc"])
            N[f"{M}Markup{tag}OtherTPR"] = f3(r["mean_tpr_non_saa_0.05"])
        others = [r for r in recs if r["bank_seed"] != ship]
        for arm, tag in (("insert3", "Insert"), ("insert3_control", "Control"), ("remove", "Remove"),
                         ("remove_control", "RemoveControl")):
            sel = [r for r in others if r["arm"] == arm]
            if not sel:
                continue
            base = {r["bank_seed"]: r for r in others if r["arm"] == "none"}
            N[f"{M}Markup{tag}Banks"] = str(len(sel))
            N[f"{M}Markup{tag}SAAAUROCmed"] = f3(float(np.median([r["saa_auroc"] for r in sel])))
            N[f"{M}Markup{tag}BaseSAAAUROCmed"] = f3(float(np.median([base[r["bank_seed"]]["saa_auroc"] for r in sel])))
            N[f"{M}Markup{tag}MeanAUROCmed"] = f3(float(np.median([r["mean_auroc"] for r in sel])))
            N[f"{M}Markup{tag}BaseMeanAUROCmed"] = f3(float(np.median([base[r["bank_seed"]]["mean_auroc"] for r in sel])))
            N[f"{M}Markup{tag}SAATPRmed"] = f3(float(np.median([r["saa_tpr_0.05"] for r in sel])))
            N[f"{M}Markup{tag}SAATPRmax"] = f3(max(r["saa_tpr_0.05"] for r in sel))
            N[f"{M}Markup{tag}SAATPRtenmax"] = f3(max(r["saa_tpr_0.1"] for r in sel))
            d = [r["saa_auroc"] - base[r["bank_seed"]]["saa_auroc"] for r in sel]
            N[f"{M}Markup{tag}DeltaSAAAUROCmed"] = f"{np.median(d):+.3f}"
            N[f"{M}Markup{tag}DeltaSAAAUROCmin"] = f"{min(d):+.3f}"
            N[f"{M}Markup{tag}DeltaSAAAUROCmax"] = f"{max(d):+.3f}"
            dm = [r["mean_auroc"] - base[r["bank_seed"]]["mean_auroc"] for r in sel]
            N[f"{M}Markup{tag}DeltaMeanAUROCmed"] = f"{np.median(dm):+.3f}"
    if L[-1] == r"\midrule":
        L.pop()
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    if any_markup:
        (GEN / "tab_markup.tex").write_text("\n".join(L) + "\n")
    else:
        (GEN / "tab_markup.tex").write_text(r"\missing{} % markup test not yet run" + "\n")
        missing("markup")


def sentinel_shift(N, m, ship):
    """Why placed anchors backfire on Mistral: where the benign and attack scores sit relative to the threshold."""
    from mtkaudit import release as rd
    fp = rd.import_release()
    lay = json.loads((rd.OUT / m / "rows.json").read_text())["release_cache"]
    ds, seed = lay["datasets"], SHIPPED[m]
    b = ds[rd.BENIGN_DATASET]
    ev = [b["feature_row"][p] for p in rd.sampled_positions(fp, b["n"], seed, rd.BENIGN_DATASET)]
    att = [info["feature_row"][p] for n, info in ds.items() if n not in (rd.BENIGN_DATASET, "saa")
           for p in rd.sampled_positions(fp, info["n"], seed, n)]
    for arm, dose, tag in (("none", 0, "None"), ("nosuffix", 200, "Nosuf"), ("shufsuffix", 200, "Shuf")):
        r = next((r for r in ship if r["arm"] == arm and r["dose"] == dose), None)
        f = RP / "sentinel_v2" / "scores" / f"{m}_bank{seed}_{arm}_N{dose}.npy"
        if r is None or not f.exists():
            continue
        sc = np.load(f).astype(float)
        t = r["metrics"]["thresholds"]["0.05"]
        M = MMAC[m]
        N[f"{M}SentShip{tag}Thr"] = f3(t)
        N[f"{M}SentShip{tag}BenMed"] = f"{np.median(sc[ev]):+.3f}"
        N[f"{M}SentShip{tag}AttMargin"] = f"{np.median(sc[att]) - t:+.3f}"


def sentinel(N):
    rows = {}
    for m in MODELS:
        p = RP / "sentinel_v2" / f"{m}.jsonl"
        if p.exists():
            rows[m] = [json.loads(l) for l in p.read_text().splitlines()]
    if not rows:
        (GEN / "tab_sentinel.tex").write_text(r"\missing{} % sentinel not yet run" + "\n")
        missing("sentinel")
        return
    arms = [("none", 0, "none (as drawn)"), ("ordinary", 200, "ordinary PKU"), ("nosuffix", 200, "template"),
            ("shufsuffix", 200, "template + shuffled"), ("randsuffix", 200, "template + random")]
    L = [r"\begin{table*}[t]", r"\centering",
         r"\caption{Anchors placed on purpose, through the release pipeline: 200 of the 600 PKU anchors replaced "
         r"at positions fixed per bank and shared by every arm. Template anchors wrap goals from the defender's "
         r"half of SAA-850 in the public SAA template (no suffix, the released suffix shuffled, or random "
         r"tokens; one draw of goals per bank, shared by the three); SAA is detection on the other half. Other: "
         r"mean detection over the eleven untargeted "
         r"families. Mean over the configured seed and seeds 0 and 1; 5\% budget, recalibrated per arm.}",
         r"\label{tab:sentinel}", r"\footnotesize", r"\setlength{\tabcolsep}{2pt}",
         r"\begin{tabular}{l" + "rr" * len(rows) + "}", r"\toprule",
         " & " + " & ".join(rf"\multicolumn{{2}}{{c}}{{{MNAME[m]}}}" for m in rows) + r" \\",
         " ".join(rf"\cmidrule(lr){{{2 + 2 * i}-{3 + 2 * i}}}" for i in range(len(rows))),
         "Replaced by & " + " & ".join(["SAA & Other"] * len(rows)) + r" \\", r"\midrule"]
    for arm, dose, label in arms:
        cells = []
        for m, recs in rows.items():
            sel = [r for r in recs if r["arm"] == arm and r["dose"] == dose]
            if len(sel) < 3:
                cells += [missing(f"sentinel {m} {arm}")] * 2
                continue
            cells += [f3(np.mean([r["saa850_eval_half"]["tpr_0.05"] for r in sel])),
                      f3(np.mean([r["mean_tpr_non_saa_0.05"] for r in sel]))]
        L.append(f"{label} & " + " & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    (GEN / "tab_sentinel.tex").write_text("\n".join(L) + "\n")
    for m, recs in rows.items():
        M = MMAC[m]
        t200 = [r for r in recs if r["arm"] in ("nosuffix", "shufsuffix", "randsuffix") and r["dose"] == 200]
        if t200:
            sa = [r["saa850_eval_half"]["tpr_0.05"] for r in t200]
            ot = [r["mean_tpr_non_saa_0.05"] for r in t200]
            N[f"{M}SentTwoTmplSAAmin"], N[f"{M}SentTwoTmplSAAmax"] = f3(min(sa)), f3(max(sa))
            N[f"{M}SentTwoTmplOthermin"], N[f"{M}SentTwoTmplOthermax"] = f3(min(ot)), f3(max(ot))
            N[f"{M}SentTwoTmplHigh"] = str(sum(x >= 0.95 for x in sa))
            rng = lambda v: f3(min(v)) if f3(min(v)) == f3(max(v)) else f"{f3(min(v))}--{f3(max(v))}"
            N[f"{M}SentTwoTmplSAArange"] = rng(sa)
            N[f"{M}SentTwoTmplOtherrange"] = rng(ot)
            N[f"{M}SentTwoTmplN"] = str(len(sa))
            # change in the untargeted families against the same bank with nothing replaced
            base = {r["bank_seed"]: r["mean_tpr_non_saa_0.05"] for r in recs if r["arm"] == "none" and r["dose"] == 0}
            dl = [r["mean_tpr_non_saa_0.05"] - base[r["bank_seed"]] for r in t200 if r["bank_seed"] in base]
            if dl:
                N[f"{M}SentTwoTmplDeltaMin"], N[f"{M}SentTwoTmplDeltaMax"] = f"{min(dl):+.3f}", f"{max(dl):+.3f}"
                N[f"{M}SentTwoTmplCostN"] = str(sum(d < 0 for d in dl))
                N[f"{M}SentTwoTmplMaxLoss"] = f3(max(0.0, -min(dl)))
        tmpl = [r for r in recs if r["arm"] in ("nosuffix", "shufsuffix", "randsuffix")]
        if tmpl:
            N[f"{M}SentTmplSAAmin"] = f3(min(r["saa850_eval_half"]["tpr_0.05"] for r in tmpl))
            N[f"{M}SentTmplSAAmax"] = f3(max(r["saa850_eval_half"]["tpr_0.05"] for r in tmpl))
            N[f"{M}SentTmplOthermin"] = f3(min(r["mean_tpr_non_saa_0.05"] for r in tmpl))
            N[f"{M}SentTmplOthermax"] = f3(max(r["mean_tpr_non_saa_0.05"] for r in tmpl))
            N[f"{M}SentTmplMeanAUROCmin"] = f3(min(r["metrics"]["mean_auroc"] for r in tmpl))
            N[f"{M}SentTmplPMPmax"] = f3(max(r["pmp_fpr_0.05"] for r in tmpl))
            N[f"{M}SentTmplN"] = str(len(tmpl))
            N[f"{M}SentTmplHigh"] = str(sum(r["saa850_eval_half"]["tpr_0.05"] > 0.8 for r in tmpl))
        for arm, tag in (("none", "None"), ("ordinary", "Ordinary"), ("nosuffix", "Nosuf"),
                         ("shufsuffix", "Shuf"), ("randsuffix", "Rand")):
            sel = [r for r in recs if r["arm"] == arm and r["dose"] == (0 if arm == "none" else 200)]
            if not sel:
                continue
            N[f"{M}Sent{tag}SAA"] = f3(np.mean([r["saa850_eval_half"]["tpr_0.05"] for r in sel]))
            N[f"{M}Sent{tag}Other"] = f3(np.mean([r["mean_tpr_non_saa_0.05"] for r in sel]))
            N[f"{M}Sent{tag}FPR"] = f3(np.mean([r["realised_fpr_0.05"] for r in sel]))
            N[f"{M}Sent{tag}PMP"] = f3(np.mean([r["pmp_fpr_0.05"] for r in sel]))
            N[f"{M}Sent{tag}EASR"] = f3(np.mean([r["saa850_eval_half"]["easr_harmbench_0.05"] for r in sel]))
            N[f"{M}Sent{tag}MeanAUROC"] = f3(np.mean([r["metrics"]["mean_auroc"] for r in sel]))
        ship = [r for r in recs if r["bank_seed"] == SHIPPED[m]]
        if m == "mistral":
            sentinel_shift(N, m, ship)
            for b, w in ((0, "Zero"), (1, "One")):
                for arm, tag in (("none", "None"), ("nosuffix", "Nosuf"), ("shufsuffix", "Shuf")):
                    r = next((r for r in recs if r["bank_seed"] == b and r["arm"] == arm
                              and r["dose"] == (0 if arm == "none" else 200)), None)
                    if r:
                        N[f"MisSentBank{w}{tag}SAA"] = f3(r["saa850_eval_half"]["tpr_0.05"])
        for r in ship:
            if r["arm"] in ("none", "nosuffix") and r["dose"] in (0, 200):
                tag = "ShipNone" if r["arm"] == "none" else "ShipNosuf"
                N[f"{M}Sent{tag}SAA"] = f3(r["saa850_eval_half"]["tpr_0.05"])
                N[f"{M}Sent{tag}Other"] = f3(r["mean_tpr_non_saa_0.05"])
                N[f"{M}Sent{tag}MeanAUROC"] = f3(r["metrics"]["mean_auroc"])


# ------------------------------------------------------------------------------------------------ #
def r4(N):
    """Detector-comparison macros, all from per-prompt scores with the text-disjoint calibration set."""
    for m in ("llama2", "llama3", "mistral", "vicuna"):
        items, dets = matched_scores(m)
        if items is None:
            continue
        for name, D in DCODE.items():
            if name not in dets:
                continue
            b = budget_metrics(m, items, dets[name])
            M = MMAC[m]
            N[f"{M}{D}MeanAUROC"] = f3(b["mean_auroc"])
            N[f"{M}{D}MeanTPR"] = f3(b["mean_tpr"][0.05])
            N[f"{M}{D}SAAAUROC"] = f3(b["saa_auroc"])
            N[f"{M}{D}SAATPR"] = f3(b["saa_tpr"][0.05])
            N[f"{M}{D}SAATPRten"] = f3(b["saa_tpr10"])
            N[f"{M}{D}ZuluTPR"] = f3(b["families"]["zulu"]["tpr"][0.05])
            N[f"{M}{D}FPR"] = f3(b["fpr"][0.05])
            N[f"{M}{D}SAAeightEASR"] = f3(b["saa850_easr"])
    # GradSafe on Llama-2 at its native threshold (0.25): independent of calibration
    items, dets = matched_scores("llama2")
    if items is not None and "GradSafe" in dets:
        from mtkaudit import release as rd
        s_ = dets["GradSafe"]
        rows = lambda p, f=None: [i["row"] for i in items if i["population"] == p and (f is None or i["family"] == f)]
        rep = [i for i in items if i["population"] == "saa850_repaired"]
        x850 = s_[[i["row"] for i in rep]]
        hb = np.array([rd.load_judged("llama2")["harmbench"][int(i["source_index"])]
                       for i in rep], bool)
        N["LtwoGSNativeSAATPR"] = f3(float((s_[rows("release_attack", "saa")] >= 0.25).mean()))
        N["LtwoGSNativeSAAeightTPR"] = f3(float((x850 >= 0.25).mean()))
        N["LtwoGSNativeEASR"] = f3(float((hb & ~(x850 >= 0.25)).mean()))
        N["LtwoGSNativeFPR"] = f3(float((s_[rows("benign_eval")] >= 0.25).mean()))
        # the reference lottery: official reference plus the redraws, same calibration rule
        vals = []
        for f in [RES / "gradsafe/scores_official.jsonl"] + sorted((RES / "gradsafe").glob("scores_refset*.jsonl")):
            sc = {json.loads(l)["row"]: json.loads(l)["score"] for l in f.read_text().splitlines()}
            if len(sc) != len(items):
                continue
            b = budget_metrics("llama2", items, np.array([sc[i["row"]] for i in items]))
            vals.append((b, f.name))
        if len(vals) > 1:
            N["GSRefsets"] = str(len(vals) - 1)
            sa = [b["saa_tpr"][0.05] for b, _ in vals]
            au = [b["saa_auroc"] for b, _ in vals]
            ma = [b["mean_auroc"] for b, _ in vals]
            N["GSRefSAATPRmin"], N["GSRefSAATPRmax"] = f3(min(sa)), f3(max(sa))
            N["GSRefSAAAUROCmin"], N["GSRefSAAAUROCmax"] = f3(min(au)), f3(max(au))
            N["GSRefMeanAUROCmin"], N["GSRefMeanAUROCmax"] = f3(min(ma)), f3(max(ma))


_MED: dict = {}
_SD: dict = {}

def budget_table(N):
    import csv
    L = [r"\begin{table*}[t]", r"\centering",
         r"\caption{AUROC and detection at false-positive budgets of 1\% and 5\% (2--4\% in the released evidence), for every detector on every model, on "
         r"identical prompts. Each threshold is the $(1-\alpha)$ quantile of the same held-out benign prompts "
         r"(\nCalShipMin--\nCalShipMax, sharing no text with the evaluated ones); FPR: the rate it realises on the release's 500 evaluated benign prompts. "
         r"Left: mean over the twelve released families. Right: the released SAA sample. eASR: share of the "
         r"850 SAA prompts that receive a classifier-judged harmful response (HarmBench / StrongREJECT) and pass the detector at 5\%. "
         r"GradSafe on Llama-3, Mistral and Vicuna is our port (chat template only); HiddenDetect is the LLM "
         r"adaptation (layers 16--29); the linear probe is logistic regression trained on MTK's 1{,}600 reference "
         r"prompts at MTK's read position. Rows are grouped by model.}",
         r"\label{tab:budget}", r"\footnotesize", r"\setlength{\tabcolsep}{3pt}",
         r"\begin{tabular}{ll" + "rrr" + "rrr" + "rrr}", r"\toprule",
         r" & & \multicolumn{3}{c}{Mean over 12 families} & \multicolumn{3}{c}{SAA} & \multicolumn{2}{c}{FPR} & \\",
         r"\cmidrule(lr){3-5} \cmidrule(lr){6-8} \cmidrule(lr){9-10}",
         r"Model & Detector & AUROC & 1\% & 5\% & AUROC & 1\% & 5\% & 1\% & 5\% & eASR \\",
         r"\midrule"]
    csv_rows = []
    for m in MODELS:
        items, dets = matched_scores(m)
        first = True
        for name, _ in DETECTORS:
            label = name + (" (port)" if name == "GradSafe" and m != "llama2" else "")
            head = MNAME[m] if first else ""
            if items is None or name not in dets:
                L.append(f"{head} & {label} & " + " & ".join([missing(f"budget {m} {name}")] * 9) + r" \\")
                first = False
                continue
            b = budget_metrics(m, items, dets[name])
            cells = [f3(b["mean_auroc"])] + [f3(b["mean_tpr"][t]) for t in (0.01, 0.05)] + \
                    [f3(b["saa_auroc"])] + [f3(b["saa_tpr"][t]) for t in (0.01, 0.05)] + \
                    [f3(b["fpr"][0.01]), f3(b["fpr"][0.05]), f"{b['saa850_easr']:.2f}/{b['saa850_easr_sr']:.2f}"]
            L.append(f"{head} & {label} & " + " & ".join(cells) + r" \\")
            first = False
            M, D = MMAC[m], DCODE[name]
            for t, w in zip(BUDGETS, ("one", "two", "three", "four", "five")):
                N[f"{M}{D}BudgetMeanTPR{w}"] = f3(b["mean_tpr"][t])
                N[f"{M}{D}BudgetSAATPR{w}"] = f3(b["saa_tpr"][t])
            N[f"{M}{D}BudgetMeanAUROC"] = f3(b["mean_auroc"])
            N[f"{M}{D}BudgetSAAAUROC"] = f3(b["saa_auroc"])
            N[f"{M}{D}BudgetSAAAUROCfour"] = f"{b['saa_auroc']:.4f}"
            N[f"{M}{D}BudgetFPR"] = f3(b["fpr"][0.05])
            N[f"{M}{D}BudgetFPRone"] = f3(b["fpr"][0.01])
            N[f"{M}{D}BudgetEASRsr"] = f3(b["saa850_easr_sr"])
            N[f"{M}{D}BudgetEASR"] = f3(b["saa850_easr"])
            for f, v in b["families"].items():
                csv_rows.append({"model": m, "detector": label, "family": FAM[f], "n": v["n"],
                                 "auroc": round(v["auroc"], 4),
                                 **{f"tpr_{int(t * 100)}pct": round(v["tpr"][t], 4) for t in BUDGETS},
                                 **{f"realised_fpr_{int(t * 100)}pct": round(b["fpr"][t], 4) for t in BUDGETS}})
        L.append(r"\midrule")
    L.pop()
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    (GEN / "tab_budget.tex").write_text("\n".join(L) + "\n")
    # realised FPR ranges over all 16 detector-model pairs at the nominal 1% and 5% budgets
    allb = [budget_metrics(m, *matched_scores_one(m, d)) for m in MODELS for d, _ in DETECTORS
            if matched_scores_one(m, d)[1] is not None]
    if allb:
        for t, w in ((0.01, "One"), (0.05, "Five")):
            N[f"BudgetFPR{w}Min"] = f3(min(b["fpr"][t] for b in allb))
            N[f"BudgetFPR{w}Max"] = f3(max(b["fpr"][t] for b in allb))
    # summary counts over the internal-signal detectors (not perplexity)
    for group, dets_ in (("", INTERNAL), ("Pub", ("MTK", "GradSafe", "HiddenDetect"))):
        cs = [(m, d, budget_metrics(m, *matched_scores_one(m, d))) for m in MODELS for d in dets_
              if matched_scores_one(m, d)[1] is not None]
        if not cs:
            continue
        N[f"Budget{group}NCells"] = str(len(cs))
        N[f"Budget{group}TopMeanTPRone"] = f3(max(b["mean_tpr"][0.01] for _, _, b in cs))
        N[f"Budget{group}SAAMissedAny"] = str(sum(b["saa_tpr"][0.05] < 0.2 for _, _, b in cs))
        for cut, w in ((0.80, "Eighty"), (0.85, "EightyFive"), (0.90, "Ninety")):
            N[f"Budget{group}SAAHidden{w}"] = str(sum(b["saa_auroc"] >= cut and b["saa_tpr"][0.05] < 0.2 for _, _, b in cs))
            N[f"Budget{group}FamHidden{w}"] = str(sum(1 for _, _, b in cs for v in b["families"].values()
                                                     if v["n"] >= 50 and v["auroc"] >= cut and v["tpr"][0.05] < 0.2))
            N[f"Budget{group}DetsHidden{w}"] = str(len({d for _, d, b in cs for v in b["families"].values()
                                                       if v["n"] >= 50 and v["auroc"] >= cut and v["tpr"][0.05] < 0.2}))
        N[f"Budget{group}ModelsWithHiddenFamily"] = str(len({(m, d) for m, d, b in cs for v in b["families"].values()
                                                             if v["n"] >= 50 and v["auroc"] >= 0.85 and v["tpr"][0.05] < 0.2}))
        N[f"Budget{group}ModelsWithFamilyMissed"] = str(len({(m, d) for m, d, b in cs for v in b["families"].values()
                                                             if v["n"] >= 50 and v["tpr"][0.05] < 0.2}))
        # the same pair counts at other AUROC cut-offs, and without SAA (is the effect one attack's?)
        hid = lambda b, cut, skip=(): [f for f, v in b["families"].items()
                                       if f not in skip and v["n"] >= 50 and v["auroc"] >= cut and v["tpr"][0.05] < 0.2]
        for cut, w in ((0.80, "Eighty"), (0.90, "Ninety")):
            N[f"Budget{group}ModelsWithHiddenFamily{w}"] = str(sum(bool(hid(b, cut)) for _, _, b in cs))
        N[f"Budget{group}ModelsWithHiddenFamilyNoSAA"] = str(sum(bool(hid(b, 0.85, ("saa",))) for _, _, b in cs))
        N[f"Budget{group}NoSAAHiddenZulu"] = str(sum("zulu" in hid(b, 0.85, ("saa",)) for _, _, b in cs))
        N[f"Budget{group}ModelsWithFamilyMissedNoSAA"] = str(sum(
            any(f != "saa" and v["n"] >= 50 and v["tpr"][0.05] < 0.2 for f, v in b["families"].items()) for _, _, b in cs))
    # the probe's cross-validated AUROC on the anchors at its chosen layer (probe_baseline.py); floored, the text says "at least"
    cvs = [max(json.loads((RES / "matched_detectors" / m / "probe_manifest.json").read_text())["cv_auroc_by_layer"])
           for m in MODELS]
    N["ProbeCVMin"] = f"{int(min(cvs) * 1000) / 1000:.3f}"
    cells = [(m, d, budget_metrics(m, *matched_scores_one(m, d))) for m in MODELS for d in ("MTK", "GradSafe", "HiddenDetect")
             if matched_scores_one(m, d)[1] is not None]
    if cells:
        N["BudgetCells"] = str(len(cells))
        N["BudgetMaxMeanTPRone"] = f3(max(b["mean_tpr"][0.01] for _, _, b in cells))
        N["BudgetMaxMeanAUROC"] = f3(max(b["mean_auroc"] for _, _, b in cells))
        hidden = [(m, d) for m, d, b in cells if b["saa_auroc"] >= 0.85 and b["saa_tpr"][0.05] < 0.2]
        N["BudgetSAAHidden"] = str(len(hidden))
        N["BudgetSAAMissed"] = str(sum(b["saa_tpr"][0.05] < 0.2 for _, _, b in cells))
        N["BudgetSAACaught"] = str(sum(b["saa_tpr"][0.05] >= 0.5 for _, _, b in cells))
        fam_hidden = sum(1 for _, _, b in cells for v in b["families"].values()
                         if v["n"] >= 50 and v["auroc"] >= 0.85 and v["tpr"][0.05] < 0.2)
        N["BudgetFamHidden"] = str(fam_hidden)
        ppl = [budget_metrics(m, *matched_scores_one(m, "Windowed PPL"))["mean_auroc"] for m in MODELS
               if matched_scores_one(m, "Windowed PPL")[1] is not None]
        if ppl:
            N["PPLMeanAUROCmin"], N["PPLMeanAUROCmax"] = f3(min(ppl)), f3(max(ppl))
        N["BudgetDetsWithHidden"] = str(len({d for _, d, b in cells for v in b["families"].values()
                                             if v["n"] >= 50 and v["auroc"] >= 0.85 and v["tpr"][0.05] < 0.2}))
    # our HiddenDetect adaptation against the HiddenDetect AUROCs MTK's Table 4 reports
    try:
        import sys
        sys.path.insert(0, str(ROOT))
        from mtkaudit.baselines import MTK_TABLE4_HIDDENDETECT as T4
        keys = {"autodan": ["autodan_1"], "drattack": ["drattack_1"], "ijp": ["ijp_1"],
                "JailJudge": ["JailJudge_1"], "JailJudge_all": ["JailJudge_all_1"], "nanogcg": ["nanogcg_1"],
                "nonagcg": ["nonagcg_1"], "pair": ["pair_1"], "pap_gpt4": ["pap_gpt4_1"], "saa": ["saa_1"],
                "tap": ["tap_1"], "zulu": ["zulu_1"]}
        for m in MODELS:
            items, s_hd = matched_scores_one(m, "HiddenDetect")
            if s_hd is None:
                continue
            b = budget_metrics(m, items, s_hd)
            pairs = [(v["auroc"], T4[m][k]) for f, v in b["families"].items() for k in keys.get(f, []) if k in T4[m]]
            N[f"{MMAC[m]}HDvsMTKdiff"] = f3(float(np.mean([abs(a - r) for a, r in pairs])))
            N[f"{MMAC[m]}HDoursMean"] = f3(float(np.mean([a for a, _ in pairs])))
            N[f"{MMAC[m]}HDtheirsMean"] = f3(float(np.mean([r for _, r in pairs])))
    except ImportError:
        pass
    if csv_rows:
        path = RES / "matched_detectors" / "budget_per_family.csv"
        with path.open("w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=list(csv_rows[0]))
            w.writeheader()
            w.writerows(csv_rows)


def calib_table(N):
    """Dolly-set vs real-traffic 5% thresholds for every detector (results/dolly_calibration/summary.json)."""
    p = RES / "dolly_calibration" / "summary_v2.json"   # text-disjoint Dolly split (dolly_split_v2.py)
    if not p.exists():
        (GEN / "tab_calib.tex").write_text(r"\missing{}" + "\n")
        missing("dolly calibration")
        return
    sm = json.loads(p.read_text())
    wp = RES / "wildchat" / "summary.json"                 # second real-user distribution (wildchat_summary.py)
    wc = json.loads(wp.read_text()) if wp.exists() else {}
    order = (("MTK", "MTK"), ("Probe", "Linear probe"), ("GradSafe", "GradSafe"), ("HiddenDetect", "HiddenDetect"),
             ("Windowed PPL", "Windowed PPL"))
    L = [r"\begin{table*}[t]", r"\centering",
         r"\caption{Which benign prompts set the threshold. Each detector's 5\% threshold is set either on about 200 "
         r"held-out Databricks-Dolly prompts (\nDollyCalNMin--\nDollyCalNMax, distinct texts), the calibration protocol of MTK's paper, or on held-out real "
         r"ToxicChat user prompts (real; ours). FPR$_\mathrm{TC}$, FPR$_\mathrm{WC}$: false-positive rate the Dolly-set threshold "
         r"realises on the release's 500 evaluated ToxicChat prompts and on 500 held-out WildChat prompts, a second real-user "
         r"distribution (on \nDollyEvalNMin--\nDollyEvalNMax\ further Dolly prompts it realises about 5\%). Det.: mean "
         r"detection over the twelve families under the Dolly-set or the ToxicChat-set (TC) threshold. The linear probe is trained on MTK's "
         r"reference bank; GradSafe is the official code on Llama-2 and our port elsewhere.}",
         r"\label{tab:calib}", r"\footnotesize", r"\setlength{\tabcolsep}{3pt}",
         r"\begin{tabular}{l" + "rrrr" * len(MODELS) + "}", r"\toprule",
         " & " + " & ".join(rf"\multicolumn{{4}}{{c}}{{{MNAME[m]}}}" for m in MODELS) + r" \\",
         " ".join(rf"\cmidrule(lr){{{2 + 4 * i}-{5 + 4 * i}}}" for i in range(len(MODELS))),
         "Threshold from & " + " & ".join(["Dolly & Dolly & Dolly & TC"] * len(MODELS)) + r" \\",
         "Measured & " + " & ".join([r"FPR$_\mathrm{TC}$ & FPR$_\mathrm{WC}$ & Det. & Det."] * len(MODELS)) + r" \\", r"\midrule"]
    ranges = {}
    for key, label in order:
        cells = []
        for m in MODELS:
            r = sm.get(m, {}).get(key)
            w = wc.get(m, {}).get(key)
            if r is None or w is None:
                cells += [missing(f"calib {m} {key}")] * 4
                continue
            d, t = r["dolly"], r["toxicchat"]
            cells += [f3(d["fpr_toxicchat_eval"]), f3(w["dolly"]["fpr_wildchat_eval"]), f3(d["mean_tpr"]), f3(t["mean_tpr"])]
            M, D = MMAC[m], DCODE.get(label, "LP")
            N[f"Calib{M}{D}FPRreal"] = f3(d["fpr_toxicchat_eval"])
            N[f"Calib{M}{D}FPRreallo"], N[f"Calib{M}{D}FPRrealhi"] = f3(d["fpr_toxicchat_eval_ci"][0]), f3(d["fpr_toxicchat_eval_ci"][1])
            N[f"Calib{M}{D}FPRdolly"] = f3(d["fpr_dolly_eval"])
            N[f"Calib{M}{D}DetDolly"], N[f"Calib{M}{D}DetReal"] = f3(d["mean_tpr"]), f3(t["mean_tpr"])
            N[f"Calib{M}{D}SAADolly"], N[f"Calib{M}{D}SAAReal"] = f3(d["saa_tpr"]), f3(t["saa_tpr"])
            ranges.setdefault(D, []).append((m, d["fpr_toxicchat_eval"], d["mean_tpr"], t["mean_tpr"], d["fpr_dolly_eval"]))
        L.append(f"{label} & " + " & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    (GEN / "tab_calib.tex").write_text("\n".join(L) + "\n")
    for D, v in ranges.items():
        N[f"Calib{D}FPRrealMin"], N[f"Calib{D}FPRrealMax"] = f3(min(x[1] for x in v)), f3(max(x[1] for x in v))
        N[f"Calib{D}DetDollyMin"], N[f"Calib{D}DetDollyMax"] = f3(min(x[2] for x in v)), f3(max(x[2] for x in v))
        N[f"Calib{D}DetRealMin"], N[f"Calib{D}DetRealMax"] = f3(min(x[3] for x in v)), f3(max(x[3] for x in v))
        N[f"Calib{D}FPRdollyMin"], N[f"Calib{D}FPRdollyMax"] = f3(min(x[4] for x in v)), f3(max(x[4] for x in v))
    N["CalibMTKFPRratioMin"] = f"{min(x[1] for x in ranges['MTK']) / 0.05:.1f}"
    N["CalibMTKFPRratioMax"] = f"{max(x[1] for x in ranges['MTK']) / 0.05:.1f}"
    ports = [x for x in ranges.get("GS", []) if x[0] != "llama2"]
    if ports:
        N["CalibGSPortFPRrealMin"], N["CalibGSPortFPRrealMax"] = f3(min(x[1] for x in ports)), f3(max(x[1] for x in ports))
    # the other detectors' Dolly runs rescore 40 evaluated prompts; largest difference from the saved scores
    od = RES / "dolly_calibration" / "other_detectors"
    probe_d, other_d = [], []
    for m in MODELS:
        for f in (od / f"{m}_consistency.json", od / f"{m}_gradsafe_consistency.json"):
            if f.exists():
                for k, v in json.loads(f.read_text()).items():
                    (probe_d if k == "Probe" else other_d).append(v)
    if probe_d and other_d:
        N["DollyConsistProbe"] = f"{max(probe_d):.3f}"
        e = int(np.floor(np.log10(max(other_d))))
        N["DollyConsistOther"] = rf"{max(other_d) / 10 ** e:.0f}\times10^{{{e}}}"
    # equal-size control: ToxicChat thresholds from as many prompts as the Dolly set (calib_size_control.py)
    sc_p = RES / "dolly_calibration" / "size_control.json"
    if sc_p.exists():
        sc = json.loads(sc_p.read_text())
        mt_ = [sc["models"][m]["detectors"]["MTK"] for m in MODELS]
        al_ = [v for m in MODELS for v in sc["models"][m]["detectors"].values()]
        N["SizeCtrlB"] = f"{sc['B']:,}".replace(",", "{,}")
        N["SizeCtrlMTKMedMin"], N["SizeCtrlMTKMedMax"] = f3(min(r["fpr_toxicchat_eval"][1] for r in mt_)), f3(max(r["fpr_toxicchat_eval"][1] for r in mt_))
        N["SizeCtrlMTKHiMax"] = f3(max(r["fpr_toxicchat_eval"][2] for r in mt_))
        N["SizeCtrlMTKShareMax"] = f3(max(r["share_subsamples_fpr_at_least_dolly"] for r in mt_))
        N["SizeCtrlAllMedMin"], N["SizeCtrlAllMedMax"] = f3(min(r["fpr_toxicchat_eval"][1] for r in al_)), f3(max(r["fpr_toxicchat_eval"][1] for r in al_))
    # the GCG-type family behind MTK's 95%-at-5% (its Table 3: GCG on Llama-2)
    g = sm["llama2"]["MTK"]
    N["CalibLtwoNanoDolly"] = f3(g["dolly"]["families"]["nanogcg"])
    N["CalibLtwoNanoReal"] = f3(g["toxicchat"]["families"]["nanogcg"])
    N["CalibLtwoNanoN"] = str(g["dolly"]["family_n"]["nanogcg"])
    N["CalibLtwoNanoK"] = str(g["dolly"]["family_detected"]["nanogcg"])
    _bs = json.loads((RES / "uncertainty" / "bootstrap.json").read_text())["models"]["llama2"]["detectors"]["MTK"]
    N["CalibLtwoNanoRealCIlo"], N["CalibLtwoNanoRealCIhi"] = (f"{_bs['tpr_nanogcg_0.05']['lo']:.2f}",
                                                              f"{_bs['tpr_nanogcg_0.05']['hi']:.2f}")
    gi_p = RES / "dolly_calibration" / "gcg_interval.json"          # dolly_gcg_interval.py
    if gi_p.exists():
        gi = json.loads(gi_p.read_text())
        N["CalibLtwoNanoCIlo"], N["CalibLtwoNanoCIhi"] = f"{gi['interval'][0]:.2f}", f"{gi['interval'][1]:.2f}"
    ns = [sm[m]["_split"] for m in MODELS if m in sm]
    N["DollyCalNMin"], N["DollyCalNMax"] = str(min(x["n_calibration"] for x in ns)), str(max(x["n_calibration"] for x in ns))
    N["DollyEvalNMin"], N["DollyEvalNMax"] = str(min(x["n_evaluation"] for x in ns)), str(max(x["n_evaluation"] for x in ns))


def ensemble(N):
    """Each internal-signal detector OR windowed perplexity, each at 2.5% (budget split fixed in advance)."""
    from mtkaudit.matched import calibration_rows_v2
    res = {}
    for m in MODELS:
        items, dets = matched_scores(m)
        if items is None or "Windowed PPL" not in dets:
            continue
        rows = lambda p, f=None: [i["row"] for i in items if i["population"] == p and (f is None or i["family"] == f)]
        cal, ev = calibration_rows_v2(items), rows("benign_eval")
        fams = sorted({i["family"] for i in items if i["population"] == "release_attack"})
        ppl = dets["Windowed PPL"]
        tp = np.quantile(ppl[cal], 0.975)
        for d in INTERNAL:
            if d not in dets:
                continue
            s_ = dets[d]
            t = np.quantile(s_[cal], 0.975)
            flag = lambda r: (s_[r] > t) | (ppl[r] > tp)
            big = {f: float(flag(rows("release_attack", f)).mean()) for f in fams if len(rows("release_attack", f)) >= 50}
            worst = min(big, key=big.get)
            res[(m, d)] = {"fpr": float(flag(ev).mean()), "saa": big["saa"], "worst": worst, "worst_tpr": big[worst]}
    for m in MODELS:
        r = res.get((m, "MTK"))
        if r:
            M = MMAC[m]
            N[f"Ens{M}SAA"], N[f"Ens{M}FPR"] = f3(r["saa"]), f3(r["fpr"])
            N[f"Ens{M}Worst"], N[f"Ens{M}WorstTPR"] = FAM[r["worst"]], f3(r["worst_tpr"])
    if res:
        N["EnsN"] = str(len(res))
        N["EnsSAACaught"] = str(sum(v["saa"] >= 0.9 for v in res.values()))
        N["EnsFamilyMissed"] = str(sum(v["worst_tpr"] < 0.2 for v in res.values()))
        N["EnsFPRMin"], N["EnsFPRMax"] = f3(min(v["fpr"] for v in res.values())), f3(max(v["fpr"] for v in res.values()))


def gate(N):
    p = RP / "gate.json"
    if not p.exists():
        missing("gate")
        return
    g = json.loads(p.read_text())
    diffs = [v.get("max_abs_score_diff", v.get("worst_score_diff")) for v in g["models"].values()]
    ok = all(v.get("status") == "PASS" for v in g["models"].values())
    N["GatePass"] = "all four" if ok else missing("gate fail")
    worst = max(d for d in diffs if d is not None)
    nv = max(v.get("max_abs_score_diff", 0) for k, v in g["models"].items() if k != "vicuna")
    mant_nv, exp_nv = f"{nv:.0e}".split("e")
    N["GateMaxDiffNonVicuna"] = "0" if nv == 0 else rf"{mant_nv}\times10^{{{int(exp_nv)}}}"
    mant, exp = f"{worst:.0e}".split("e")
    N["GateMaxDiff"] = "0" if worst == 0 else rf"{mant}\times10^{{{int(exp)}}}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--strict", action="store_true")
    a = ap.parse_args()
    GEN.mkdir(parents=True, exist_ok=True)
    N = Numbers()
    sweeps = {m: load_sweep(m) for m in MODELS}
    extra = r1(N, sweeps)
    fig_calibration(N)             # Fig. 1 (fig_overview, the earlier schematic, is no longer used)
    fig_budget(extra)
    markups = {m: markup_counts(m, sweeps[m]) for m in MODELS if sweeps[m]}
    stats = r2(N, sweeps)
    fig_lottery(stats, markups)
    r3(N, sweeps, markups)
    sentinel(N)
    r4(N)
    budget_table(N)
    ci_table(N)
    calib_table(N)
    mistral_offset(N)
    anchor_length(N)
    pauc_vs_tpr(N)
    wildchat(N)
    gradsafe_v4(N)
    mtk_bank_noise(N)
    tc_labels(N)
    review3(N)
    draw_baseline(N)
    rule_x(N)
    ensemble(N)
    gate(N)
    # every \n<Name> the manuscript uses must exist; a pending one renders as a visible marker (the manuscript
    # source is not distributed, so this check runs only where a copy sits in paper/submitted)
    import re
    used = set()
    for tex in sorted((ROOT / "paper/submitted").rglob("*.tex")):
        used |= set(re.findall(r"\\n([A-Z][A-Za-z]+)", tex.read_text()))
    for name in sorted(used - set(N.items)):
        N[name] = missing(f"macro {name}")
    (GEN / "numbers.tex").write_text(N.tex())
    print(f"{len(N.items)} numbers; missing: {sorted(set(MISSING))}")
    if a.strict and MISSING:
        raise SystemExit("missing inputs")


if __name__ == "__main__":
    main()
